### ISSUE TITLE
CacheInstance() get method returns null since cache fails to populate due to depriciated method

### ISSUE THREAD

**Issue by gaduimovich** [yavijava/yavijava#110]
This is the snippet of code I am using. If your wondering vm[0] is populated and this is a VCenter 6 setup.

``` java
ServiceInstance si = new ServiceInstance(new URL(host), user, passwd, true); //host, user, password, ssl off
    Folder rootFolder = si.getRootFolder();
    ManagedEntity[] vms = new InventoryNavigator(rootFolder).searchManagedEntities("VirtualMachine");

    CacheInstance vicf = new CacheInstance(si);
    vicf.watch(vms, new String[] {"name", "runtime.powerState", "summary"});
    vicf.start();

    System.out.println(vicf.get(vms[0], "name"));
```

A Null Pointer Exception Occurs at the ManagedObjectWatcher line 118

``` java
4002 [MonitorThead for https://ottvc6-01/sdk/] ERROR com.vmware.vim.cf.ManagedObjectWatcher  - Generic Exception caught in run block of ManagedObjectWatcher.
java.lang.NullPointerException
    at com.vmware.vim25.mo.PropertyCollector.waitForUpdates(PropertyCollector.java:112)
    at com.vmware.vim.cf.ManagedObjectWatcher.run(ManagedObjectWatcher.java:118)
    at java.lang.Thread.run(Thread.java:785)
```

Line 118 happens to be a Deprecated. as of SDK4.1 therefore fails to populate

``` java
UpdateSet update = pc.waitForUpdates(version);
```

**Comment by michaelrice** [comment]
Interesting. Ive honestly never used this part of the code before. Ill see if I can get some tests written around this and get them passing.

Is this an issue that worked on some previous version of vijava that fails on yavijava? Also what version of yavijava are you using?

**Comment by gaduimovich** [comment]
I'm using the 6.0.0.1 release. I attempted as well the Orginal 5.5 vijava binary and it failed as well due to the same reason.

Edit: closed by accident

**Comment by michaelrice** [comment]
Cool. Ive been meaning to update things to use the newer methods. Ill get some functional tests written and get them passing. Thanks for reporting!

**Comment by gaduimovich** [comment]
Interesting enough there was a closed bug report from vijava 5.1 that has the same problem with cache instance.

http://sourceforge.net/p/vijava/bugs/152/

>" Getter method of CacheInstance returns null.
I think that's why ManagedObjectReference not implement equals() and hashCode() method fails to get 
the object, because MOR is key of ConcurrentHashMap that is member of ManagedObjectCache named 'items'."

**Comment by gaduimovich** [comment]
Attempted using the replacement of waitForUpdates in ManagedObjectWatcher

``` java
    WaitOptions wOptions = new WaitOptions();
    wOptions.setMaxObjectUpdates(100);
    wOptions.setMaxWaitSeconds(0);
    UpdateSet update = pc.waitForUpdatesEx(version, wOptions);
```

This still gives me a Null Pointer but more information 

``` text
1420 [MonitorThead for https://ottvc6-01/sdk/] DEBUG com.vmware.vim25.ws.WSClient  - Caught an IOException. Reading ErrorStream for results.
java.io.IOException: Server returned HTTP response code: 500 for URL: https://ottvc6-01/sdk
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1455)
    at com.ibm.net.ssl.www2.protocol.https.b.getInputStream(b.java:59)
    at com.vmware.vim25.ws.WSClient.post(WSClient.java:173)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:80)
    at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:126)
    at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
    at com.vmware.vim.cf.ManagedObjectWatcher.run(ManagedObjectWatcher.java:123)
    at java.lang.Thread.run(Thread.java:785)
1420 [MonitorThead for https://ottvc6-01/sdk/] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UpdateSet
1420 [MonitorThead for https://ottvc6-01/sdk/] ERROR com.vmware.vim25.ws.WSClient  - Exception caught while invoking method: WaitForUpdatesEx
com.vmware.vim25.NotAuthenticated
    at java.lang.J9VMInternals.newInstanceImpl(Native Method)
    at java.lang.Class.newInstance(Class.java:1932)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:200)
    at com.vmware.vim25.ws.XmlGenDom.parseSoapFault(XmlGenDom.java:141)
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:100)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:206)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:82)
    at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:126)
    at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
    at com.vmware.vim.cf.ManagedObjectWatcher.run(ManagedObjectWatcher.java:123)
    at java.lang.Thread.run(Thread.java:785)
1420 [MonitorThead for https://ottvc6-01/sdk/] ERROR com.vmware.vim.cf.ManagedObjectWatcher  - NotAuthenticated Exception caught.
com.vmware.vim25.NotAuthenticated
    at java.lang.J9VMInternals.newInstanceImpl(Native Method)
    at java.lang.Class.newInstance(Class.java:1932)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:200)
    at com.vmware.vim25.ws.XmlGenDom.parseSoapFault(XmlGenDom.java:141)
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:100)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:206)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:82)
    at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:126)
    at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
    at com.vmware.vim.cf.ManagedObjectWatcher.run(ManagedObjectWatcher.java:123)
    at java.lang.Thread.run(Thread.java:785)
```

Null from the server doesn't sound good

**Comment by michaelrice** [comment]
So I found in the source where the equals and hashCode were added, then Mr Jin did a "major refactor" according to the commit messages and it was gone after that. Maybe an oversight? I can add that back I guess.. I dont see any harm in having it

**Comment by michaelrice** [comment]
Do you have TRACE logging on com.vmware enabled where you can get the XML coming from and going to the server?

**Comment by gaduimovich** [comment]
How would I do that? Currently I just run 
    BasicConfigurator.configure();

**Comment by michaelrice** [comment]
Here is how I do it: https://github.com/yavijava/hello_world_yavijava/blob/master/src/main/resources/log4j.properties

Obviously replacing `info` with `trace`

**Comment by gaduimovich** [comment]
https://gist.github.com/gaduimovich/ec5efa055ee39083c4a3

Here is the full trace.

**Comment by gaduimovich** [comment]
https://gist.github.com/gaduimovich/8f37600679d102dec5ad 

Here's the full trace.

**Comment by gaduimovich** [comment]
Check your err-online email

**Comment by yashu2203** [comment]
I faced a similar issue. For me, I logged out the service instance without runnng CacheInstance.destroy().  writing that line before logging out service instance, fixed it.
