### ISSUE TITLE
Performance degraded with yavijava 6.0.

### ISSUE THREAD

**Issue by asdubey80** [yavijava/yavijava#123]
Hi,

We manage dvSwitch by taking its configuration backup and deploying changes.
We do configuration backup by running lot of queries. With vijava the whole operation of backup was taking 6 seconds and when we change to yavijava 6.0.01 jar , the same operation took 9 minutes.
I will try to summarize what exactly we do to take configuration backup of DVSwitch.

``` java
DistributedVirtualSwitch dvSwitch = state.dvSwitch;
DVSConfigInfo dvsCfg = dvSwitch.getConfig();
int[] vlanIds = dvSwitch.queryUsedVlanIdInDvs();
ManagedObjectReference[] uplinks = dvsCfg.getUplinkPortgroup();
String description = dvsCfg.getDescription();
String ipAddress = dvsCfg.getSwitchIpAddress();
 dvsCfg.getNumPorts()
 + dvsCfg.getMaxPorts()
+ dvsCfg.getNumStandalonePorts()
```

The above given are some methods which we trigger to get confguration of dvSwitch. We trigger many more such methods to get complete information of all dvPort groups and all ports associated with port-groups.

So if I use yavijava 6.0.01 jar it works in dvSwitch but with degraded performance. When I try to run same operation on dvSwitch which is on vSphere 5.5 it takes 9 minutes as compared to 6 seconds in case of vijava.

Kindly suggest.

**Comment by michaelrice** [comment]
Can you enable debug logging and provide the output? Please note that debug logging will also log the passwords in plain text so be sure to remove them before you post the logs.

**Comment by michaelrice** [comment]
Can you also provide me with a working sample that shows the problem you are having? Something as basic as this: https://github.com/yavijava/hello_world_yavijava That way I can profile it with both vijava 5.5 beta, and yavijava 6.0.1

**Comment by asdubey80** [comment]
I have downloaded jar file of vijava 6.0.01 and pointed pom.xml to use it.Updated pom.xml with log4j dependency Can you please tell me how can I enable debug logging here.

**Comment by asdubey80** [comment]
Following is the code snippet. We are calling following method to get configuration of dvSwitch.

``` java
 public static void copyDVSwitchRunningToNet(ConnectionProperties props,
            Interpreter interpreter) throws IOException {
        LOGGER.entering(CLASS_NAME, "copyRunningToNet");
        DummyInterpreter di = (DummyInterpreter) interpreter;
        StringBuilder spying = di.getSpying();
        StateInformation state = (StateInformation) di.getStashedInfo();
        DistributedVirtualSwitch dvSwitch = state.dvSwitch;
        StringBuilder fileContents = new StringBuilder();
        // put switch information into running config
        String contactStr = NO_SETTING;
        String contactName = NO_SETTING;
        log(spying, "DistributedVirtualSwitch.getConfig()");
        DVSConfigInfo dvsCfg = dvSwitch.getConfig();
        if (dvsCfg == null) {
            throw new IOException("Unable to access the switch configuration");
        }
        DVSContactInfo contact = dvsCfg.getContact();
        if (contact != null) {
            contactStr = contact.getContact();
            contactName = contact.getName();
        }
        if (SharedStringUtils.isEmpty(contactStr)) {
            contactStr = NO_SETTING;
        }
        if (SharedStringUtils.isEmpty(contactName)) {
            contactName = NO_SETTING;
        }
        String description = dvsCfg.getDescription();
        if (SharedStringUtils.isEmpty(description)) {
            description = NO_SETTING;
        }
        String ipAddress = dvsCfg.getSwitchIpAddress();
        if (SharedStringUtils.isEmpty(ipAddress)) {
            ipAddress = NO_SETTING;
        }
        String extensionKey = dvsCfg.getExtensionKey();
        if (SharedStringUtils.isEmpty(extensionKey)) {
            extensionKey = NO_SETTING;
        }
        String createTimeStr = NO_SETTING;
        Calendar createTime = dvsCfg.getCreateTime();
        if (createTime != null && createTime.getTime() != null) {
            createTimeStr = createTime.getTime().toString();
        }
        int[] vlanIds = dvSwitch.queryUsedVlanIdInDvs();
        StringBuilder vlans = new StringBuilder();
        if (vlanIds != null && vlanIds.length > 0) {
            for (int id : vlanIds) {
                vlans.append(" " + id);
            }
        } else {
            vlans.append(" " + NO_SETTING);
        }
        fileContents.append(
            "distributed switch: " + dvsCfg.getName()
            + "\n  switch administrator contact/details: " + contactName + "/" + contactStr
            + "\n  switch creation time: " + createTimeStr + "\n  switch description: " + description
            + "\n  switch extension key: " + extensionKey + "\n  switch IP address: " + ipAddress
            + "\n  switch number of ports: " + dvsCfg.getNumPorts()
            + "\n  switch max number of ports: " + dvsCfg.getMaxPorts()
            + "\n  switch number of standalone ports: " + dvsCfg.getNumStandalonePorts()
            + "\n  switch VLAN ID(s):" + vlans);
        if (dvsCfg.getNetworkResourceManagementEnabled() != null) {
            fileContents.append("\n  switch network resource management: "
                    + (dvsCfg.getNetworkResourceManagementEnabled()
                            ? "enabled" : "disabled"));
        }
        log(spying, "DistributedVirtualSwitch.getCapability()");
        DVSCapability capability = null;
        try {
            capability = dvSwitch.getCapability();
        } catch (Exception e) {
            if (e instanceof InvalidProperty || e.getCause() instanceof InvalidProperty) {
                LOGGER.log(Level.FINE, "error getting dvs capability", e);
            } else {
                throw new IOException(e);
            }
        }
        if (capability != null) {
            if (capability.getDvsOperationSupported() != null) {
                fileContents.append("\n  switch capability: can modify switch: "
                        + (capability.getDvsOperationSupported() ? "yes" : "no"));
            }
            if (capability.getDvPortGroupOperationSupported() != null) {
                fileContents.append("\n  switch capability: can modify portgroups: "
                        + (capability.getDvPortGroupOperationSupported() ? "yes" : "no"));
            }
            if (capability.getDvPortOperationSupported() != null) {
                fileContents.append("\n  switch capability: can modify ports: "
                        + (capability.getDvPortOperationSupported() ? "yes" : "no"));
            }
            DVSFeatureCapability feature = capability.getFeaturesSupported();
            if (feature != null) {
                fileContents.append("\n  switch capability: supports VMDirectPath: "
                        + (feature.isVmDirectPathGen2Supported() ? "yes" : "no"));
                String[] teaming = feature.getNicTeamingPolicy();
                if (teaming != null && teaming.length > 0) {
                    StringBuilder policies = new StringBuilder();
                    for (String policy : teaming) {
                        policies.append(" " + policy);
                    }
                    fileContents.append("\n  switch capability: NIC teaming policies:" + policies);
                }
                DVSNetworkResourceManagementCapability mgmt = feature.getNetworkResourceManagementCapability();
                if (mgmt != null) {
                    fileContents.append("\n  switch capability: supports network resource management: "
                        + (mgmt.isNetworkResourceManagementSupported() ? "yes" : "no")
                        + "\n  switch capability: high shares: "
                        + mgmt.getNetworkResourcePoolHighShareValue()
                        + "\n  switch capability: supports Qos Tag(802.1p): "
                        + (mgmt.isQosSupported() ? "yes" : "no")
                        + "\n  switch capability: supports user defined resource pools: "
                        + (mgmt.isUserDefinedNetworkResourcePoolsSupported() ? "yes" : "no"));
                }
            }
            DistributedVirtualSwitchHostProductSpec[] hostSpecs = capability.getCompatibleHostComponentProductInfo();
            if (hostSpecs != null && hostSpecs.length > 0) {
                for (DistributedVirtualSwitchHostProductSpec spec : hostSpecs) {
                    if (spec == null) {
                        continue;
                    }
                    fileContents.append("\n  switch capability: compatible host product: "
                            + spec.getProductLineId() + " version " + spec.getVersion());
                }
            }
        }

        VMwareDVSConfigInfo vmwCfg = null;
        if (dvsCfg instanceof VMwareDVSConfigInfo) {
            vmwCfg = (VMwareDVSConfigInfo) dvsCfg;
            log(spying, "VMwareDVSConfigInfo.getMaxMtu() = " + vmwCfg.getMaxMtu());
            log(spying, "VMwareDVSConfigInfo.getPvlanConfig())");
            fileContents.append("\n  switch max MTU: " + vmwCfg.getMaxMtu());
            VMwareDVSPvlanMapEntry[] pvlans = vmwCfg.getPvlanConfig();
            if (pvlans != null && pvlans.length > 0) {
                for (VMwareDVSPvlanMapEntry pvlan : pvlans) {
                    if (pvlan == null) {
                        continue;
                    }
                    fileContents.append("\n  switch private VLAN "
                        + "(primary/secondary/type): " + pvlan.getPrimaryVlanId() + "/"
                        + pvlan.getSecondaryVlanId() + "/" + pvlan.getPvlanType());
                }
            }
            VMwareIpfixConfig ipfix = vmwCfg.getIpfixConfig();
            if (ipfix != null) {
                String ip = ipfix.getCollectorIpAddress();
                if (ip == null) {
                    ip = NO_SETTING;
                }
                String port = NO_SETTING;
                if (ipfix.getCollectorPort() != null) {
                    port = "" + ipfix.getCollectorPort();
                }
                fileContents.append("\n  switch ipfix active flow timeout: "
                    + ipfix.getActiveFlowTimeout() + "\n  switch ipfix collector IP address: " + ip
                    + "\n  switch ipfix collector port: " + port + "\n  switch ipfix idle flow timeout: "
                    + ipfix.getIdleFlowTimeout() + "\n  switch ipfix internal flows only: "
                    + (ipfix.isInternalFlowsOnly() ? "yes" : "no") + "\n  switch ipfix sampling rate: "
                    + ipfix.getSamplingRate());
            }
            LinkDiscoveryProtocolConfig link = vmwCfg.getLinkDiscoveryProtocolConfig();
            if (link != null) {
                fileContents.append("\n  switch link discovery protocol: " + link.getProtocol()
                    + "\n  switch link discovery protocol operation: " + link.getOperation());
            }
        }
        // show uplink portgroup names (sort for consistent ordering)
        fileContents.append("\n  switch uplink portgroup(s): ");
        log(spying, "DVSConfigInfo.getUplinkPortgroup()");
        ManagedObjectReference[] uplinks = dvsCfg.getUplinkPortgroup();
        if (uplinks != null && uplinks.length > 0) {
            List<String> pgNames = new ArrayList<String>(uplinks.length);
            for (ManagedObjectReference mor : uplinks) {
                if (mor == null) {
                    continue;
                }
                log(spying, "MorUtil.createExactManagedEntity(" + mor.getVal() + ")");
                DistributedVirtualPortgroup pg =
                    (DistributedVirtualPortgroup)MorUtil.createExactManagedEntity(state.si.getServerConnection(), mor);
                if (pg != null) {
                    DVPortgroupConfigInfo pgCfgInfo = null;
                    try {
                        pgCfgInfo = pg.getConfig();
                    } catch (Exception e) {
                        if (e instanceof InvalidProperty || e.getCause() instanceof InvalidProperty) {
                            LOGGER.log(Level.FINE, "error getting port group config information", e);
                        } else {
                            throw new IOException(e);
                        }
                    }
                    if (pgCfgInfo != null) {
                        pgNames.add(pgCfgInfo.getName());
                    }
                } else {
                    // permissions might prevent reading the object
                    pgNames.add(mor.getVal());
                }
            }
            Collections.sort(pgNames);
            for (int i = 0; i < pgNames.size(); i++) {
                fileContents.append(pgNames.get(i));
                if (i < pgNames.size() - 1) {
                    fileContents.append(", ");
                 }
             }
        } else {
            fileContents.append(NO_SETTING);
        }
        log(spying, "DistributedVirtualSwitch.getNetworkResourcePool()");
        DVSNetworkResourcePool[] nrps = null;
        try {
            nrps = dvSwitch.getNetworkResourcePool();
        } catch (Exception e) {
            if (e instanceof InvalidProperty || e.getCause() instanceof InvalidProperty) {
                LOGGER.log(Level.FINE, "error getting dvs network resource pool", e);
            } else {
                throw new IOException(e);
            }
        }
        fileContents.append("\n  switch network resource pool(s): ");
        if (nrps != null && nrps.length > 0) {
            for (int i = 0; i < nrps.length; i++) {
                if (nrps[i] == null) {
                    continue;
                }
                if (i > 0) {
                    fileContents.append("; ");
                }
                fileContents.append(nrps[i].getName());
            }
        } else {
            fileContents.append(NO_SETTING);
        }
        log(spying, "DVSConfigInfo.getPolicy()");
        DVSPolicy usage = dvsCfg.getPolicy();
        if (usage != null) {
            if (usage.getAutoPreInstallAllowed() != null) {
                fileContents.append("\n  switch usage policy allow auto pre-install: "
                        + (usage.getAutoPreInstallAllowed() ? "yes" : "no"));
            }
            if (usage.getAutoUpgradeAllowed() != null) {
                fileContents.append("\n  switch usage policy allow auto upgrade: "
                        + (usage.getAutoUpgradeAllowed() ? "yes" : "no"));
            }
            if (usage.getPartialUpgradeAllowed() != null) {
                fileContents.append("\n  switch usage policy allow partial upgrade: "
                        + (usage.getPartialUpgradeAllowed() ? "yes" : "no"));
            }
        }
        StringBuilder portNames = new StringBuilder(" " + NO_SETTING);
        fileContents.append("\n  switch uplink port policy port(s):");
        DVSUplinkPortPolicy uplinkPolicy = dvsCfg.getUplinkPortPolicy();
        if (uplinkPolicy instanceof DVSNameArrayUplinkPortPolicy) {
            DVSNameArrayUplinkPortPolicy policy
                    = (DVSNameArrayUplinkPortPolicy) uplinkPolicy;
            String[] names = policy.getUplinkPortName();
            if (names != null && names.length > 9) {
                portNames = new StringBuilder();
                for (String name : names) {
                    portNames.append(" " + name);
                }
            }
        }
        fileContents.append(portNames.toString());
        fileContents.append("\n\n");
        // show member hosts and their port utilizations
        log(spying, "DVSConfigInfo.getHost()");
        DistributedVirtualSwitchHostMember[] hosts = dvsCfg.getHost();
        if (hosts != null && hosts.length > 0) {
            appendDVSMemberHostInfo(fileContents, hosts, state, spying);
        }
        log(spying, "DVSConfigInfo.getDefaultPortConfig()");
        DVPortSetting defPortCfg = dvsCfg.getDefaultPortConfig();
        if (defPortCfg != null) {
            fileContents.append("default port configuration:");
            appendPortSetting(defPortCfg, fileContents, "  default port / ", dvSwitch);
            fileContents.append("\n\n");
        }
        if (vmwCfg != null) {
            VMwareVspanSession[] sessions = vmwCfg.getVspanSession();
            if (sessions != null && sessions.length > 0) {
                for (VMwareVspanSession session : sessions) {
                    if (session == null) {
                        continue;
                    }
                    VMwareVspanPort port = session.getDestinationPort();
                    StringBuilder dstPorts = new StringBuilder(NO_SETTING);
                    if (port != null && port.getPortKey() != null && port.getPortKey().length > 0) {
                        dstPorts = new StringBuilder();
                        for (String s : port.getPortKey()) {
                            if (dstPorts.length() > 0) {
                                dstPorts.append(" ");
                            }
                            dstPorts.append(s);
                        }
                    }
                    StringBuilder dstNames = new StringBuilder(NO_SETTING);
                    if (port != null && port.getUplinkPortName() != null && port.getUplinkPortName().length > 0) {
                        dstNames = new StringBuilder();
                        for (String s : port.getUplinkPortName()) {
                            if (dstNames.length() > 0) {
                                dstNames.append("; ");
                            }
                            dstNames.append(s);
                        }
                    }
                    port = session.getSourcePortReceived();
                    StringBuilder rxPorts = new StringBuilder(NO_SETTING);
                    if (port != null && port.getPortKey() != null && port.getPortKey().length > 0) {
                        rxPorts = new StringBuilder();
                        for (String s : port.getPortKey()) {
                            if (rxPorts.length() > 0) {
                                rxPorts.append(" ");
                            }
                            rxPorts.append(s);
                        }
                    }
                    StringBuilder rxNames = new StringBuilder(NO_SETTING);
                    if (port != null && port.getUplinkPortName() != null && port.getUplinkPortName().length > 0) {
                        rxNames = new StringBuilder();
                        for (String s : port.getUplinkPortName()) {
                            if (rxNames.length() > 0) {
                                rxNames.append("; ");
                            }
                            rxNames.append(s);
                        }
                    }
                    port = session.getSourcePortTransmitted();
                    StringBuilder txPorts = new StringBuilder(NO_SETTING);
                    if (port != null && port.getPortKey() != null && port.getPortKey().length > 0) {
                        txPorts = new StringBuilder();
                        for (String s : port.getPortKey()) {
                            if (txPorts.length() > 0) {
                                txPorts.append(" ");
                            }
                            txPorts.append(s);
                        }
                    }
                    StringBuilder txNames = new StringBuilder(NO_SETTING);
                    if (port != null && port.getUplinkPortName() != null && port.getUplinkPortName().length > 0) {
                        txNames = new StringBuilder();
                        for (String s : port.getUplinkPortName()) {
                            if (txNames.length() > 0) {
                                txNames.append("; ");
                            }
                            txNames.append(s);
                        }
                    }
                    fileContents.append("distributed port mirroring session: "
                        + session.getName() + "\n  port mirror session enabled: "
                        + (session.isEnabled() ? "yes" : "no") + "\n  port mirror session description: "
                        + session.getDescription() + "\n  port mirror session encapsulation VLAN ID: "
                        + session.getEncapsulationVlanId() + "\n  port mirror session packet length: "
                        + session.getMirroredPacketLength() + "\n  port mirror session normal traffic allowed: "
                        + (session.isNormalTrafficAllowed() ? "yes" : "no")
                        + "\n  port mirror session strip original VLAN: "
                        + (session.isStripOriginalVlan() ? "yes" : "no") + "\n  port mirror session "
                        + "destination port(s): " + dstPorts + "\n  port mirror session "
                        + "destination uplink port(s): " + dstNames + "\n  port mirror session "
                        + "source port(s) (receive side): " + rxPorts + "\n  port mirror session "
                        + "source uplink port(s) (receive side): " + rxNames + "\n  port mirror session "
                        + "source port(s) (transmit side): " + txPorts + "\n  port mirror session "
                        + "source uplink port(s) (transmit side): " + txNames);
                }
                fileContents.append("\n\n");
            }
        }
        // get the ports and load into map for lookup via port keys;
        // note that sometimes port keys are numbers and sometimes names,
        // so Map must contain either
        log(spying, "DistributedVirtualSwitch.fetchDVPorts()");
        DistributedVirtualPort[] ports = dvSwitch.fetchDVPorts(new DistributedVirtualSwitchPortCriteria());
        Map dvPorts = new HashMap();
        if (ports != null && ports.length > 0) {
            try {
                for (DistributedVirtualPort p : ports) {
                    if (p != null) {
                        dvPorts.put(Integer.parseInt(p.getKey()), p);
                    }
                }
            } catch (NumberFormatException e) {
                // use strings in place of numbers
                dvPorts.clear();
                for (DistributedVirtualPort p : ports) {
                    if (p != null) {
                        dvPorts.put(p.getKey(), p);
                    }
                }
            }
        }
        // show porrgroups and ports that belong to each
        log(spying, "DistributedVirtualSwitch.getPortgroups()");
        DistributedVirtualPortgroup[] portgrps = null;
        try {
            portgrps = dvSwitch.getPortgroup();
        } catch (Exception e) {
            if (e instanceof InvalidProperty || e.getCause() instanceof InvalidProperty) {
                LOGGER.log(Level.FINE, "error getting dvs port groups", e);
            } else {
                throw new IOException(e);
            }
        }
        if (portgrps != null && portgrps.length > 0) {
            // sort portgroups to ensure consistent ordering in resuling cfg
            List<DistributedVirtualPortgroup> sortedPgs
                    = new ArrayList<DistributedVirtualPortgroup>();
            for (DistributedVirtualPortgroup pg : portgrps) {
                if (pg != null) {
                    sortedPgs.add(pg);
                }
            }
            Collections.sort(sortedPgs, new Comparator<DistributedVirtualPortgroup>() {
               /**
                * {@inheritDoc}
                 * Compares DistributedVirtualPortgroup by their names.
                */
                public int compare(DistributedVirtualPortgroup obj1,
                                   DistributedVirtualPortgroup obj2) {
                    if (obj1.getConfig() == null || obj2.getConfig() == null) {
                        return 0;
                    }
                    String s1 = obj1.getConfig().getName();
                    String s2 = obj2.getConfig().getName();
                    return ImportedStringUtils.compare(s1, s2);
                } });
            for (DistributedVirtualPortgroup pg : sortedPgs) {
                log(spying, "DistributedVirtualPortgroup.getConfig()");
                DVPortgroupConfigInfo pgCfg = null;
                String name = null;
                try {
                    pgCfg = pg.getConfig();
                } catch (Exception e) {
                    if (e instanceof InvalidProperty || e.getCause() instanceof InvalidProperty) {
                        LOGGER.log(Level.FINE, "error getting port group configuration", e);
                    } else {
                        throw new IOException(e);
                    }
                }
                if (pgCfg != null) {
                    log(spying, "DVPortgroupConfigInfo" + ".getName() = " + pgCfg.getName());
                    log(spying, "DVPortgroupConfigInfo" + ".getDescription() = " + pgCfg.getDescription());
                    name = pgCfg.getName();
                    description = pgCfg.getDescription();
                    if (SharedStringUtils.isEmpty(description)) {
                        description = NO_SETTING;
                    }
                    String format = pgCfg.getPortNameFormat();
                    if (format == null) {
                        format = NO_SETTING;
                    }
                    String autoExpand = "unsupported";
                    if (pgCfg.getAutoExpand() != null) {
                        autoExpand = (pgCfg.getAutoExpand() ? "yes" : "no");
                    }
                    fileContents.append("portgroup: " + name
                        + "\n  " + name + " / portgroup type: " + pgCfg.getType()
                        + "\n  " + name + " / description: " + description
                        + "\n  " + name + " / port name format: " + format
                        + "\n  " + name + " / auto-expand: " + autoExpand
                        + "\n  " + name + " / number of ports: " + pgCfg.getNumPorts());
                    DVPortgroupPolicy policy = pgCfg.getPolicy();
                    if (policy != null) {
                        appendDVSPortgroupPolicy(fileContents, policy, name);
                    }
                    DVPortSetting defaultSetting = pgCfg.getDefaultPortConfig();
                    if (defaultSetting != null) {
                        fileContents.append("\n  " + name + " / default port configuration:");
                        appendPortSetting(defaultSetting, fileContents, "    default port / ",  dvSwitch);
                   }
               }
                String[] portKeys = null;
                try {
                    portKeys = pg.getPortKeys();
                } catch (Exception e) {
                    if (e instanceof InvalidProperty || e.getCause() instanceof InvalidProperty) {
                        LOGGER.log(Level.FINE, "error getting port group port keys", e);
                    } else {
                        throw new IOException(e);
                    }
                }
                log(spying, "DistributedVirtualPortgroup.getPortKeys()");
                if (portKeys != null && portKeys.length > 0) {
                    // show ports in numerical order
                    List sortedPorts = getSortedPortKeys(portKeys);
                    for (Iterator ii = sortedPorts.iterator(); ii.hasNext();) {
                        Object p = ii.next();
                        DistributedVirtualPort port = (DistributedVirtualPort) dvPorts.get(p);
                        fileContents.append("\n  " + name + " / port: " + p);
                        if (port != null) {
                            appendPort(port, fileContents, state, spying, dvSwitch, "    " + p + " / ");
                        }
                    }
                }
                fileContents.append("\n\n");
            }
        }
        LOGGER.fine("running config: " + fileContents);
        props.put(DeviceTypeMap.FILE_CONTENTS_KEYWORD, fileContents.toString());
        LOGGER.exiting(CLASS_NAME, "copyRunningToNet");
    }
```

**Comment by michaelrice** [comment]
Hi @asdubey80 I have verified this as a bug and it is marked as a blocker for the next release. I have a fix pending in issue #124 please feel free to grab a copy of that code, build it and test to see if it fixes your problem.

**Comment by asdubey80** [comment]
Hey can you provide me the jar file please. I need to verify this fix and I am not able to build and create jar. 
Thanks
Ashutosh

**Comment by michaelrice** [comment]
All you need is java jdk and an internet connection. Simply run the gradle
build script.

-mike

**Comment by michaelrice** [comment]
Here is what you would need to do:

``` shell
git clone https://github.com/michaelrice/yavijava yavijava
cd yavijava
git fetch --all
git checkout issue_123
./gradlew build
```

If you are on Windows use `gradlew.bat build` instead.

This will build a jar file for you and place it in `build/libs/`

**Comment by asdubey80** [comment]
Ok I try to build with steps provided by you. The build is failing.

oEx.java:55: warning - @return tag has no arguments.
34 warnings
:javadocJar
:sourcesJar
:signArchives FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':signArchives'.
  
  > Cannot perform signing task ':signArchives' because it has no configured signa
  > tory
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 4 mins 16.203 secs

L:\Git\yavijava>gradlew build --stacktrace
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:javadoc UP-TO-DATE
:javadocJar UP-TO-DATE
:sourcesJar UP-TO-DATE
:signArchives FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':signArchives'.
  
  > Cannot perform signing task ':signArchives' because it has no configured signa
  > tory
- Try:
  Run with --info or --debug option to get more log output.
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':signArc
  hives'.
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteActions(ExecuteActionsTaskExecuter.java:69)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecute(ExecuteActionsTaskExecuter.java:46)
      at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
  uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
      at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
  ute(SkipUpToDateTaskExecuter.java:64)
      at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
  e(ValidatingTaskExecuter.java:58)
      at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
  ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
      at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
  .execute(SkipTaskWithNoActionsExecuter.java:52)
      at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
  e(SkipOnlyIfTaskExecuter.java:53)
      at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
  .execute(ExecuteAtMostOnceTaskExecuter.java:43)
      at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
  e(AbstractTask.java:296)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.executeTask(AbstractTaskPlanExecutor.java:79)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.processTask(AbstractTaskPlanExecutor.java:63)
      at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
  orker.run(AbstractTaskPlanExecutor.java:51)
      at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
  tTaskPlanExecutor.java:23)
      at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
  ltTaskGraphExecuter.java:86)
      at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
  ExecutionAction.java:29)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:61)
      at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
  uter.java:23)
      at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
  ter.java:67)
      at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
  ecutionAction.java:32)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:61)
      at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
  r.java:54)
      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
  GradleLauncher.java:148)
      at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
  Launcher.java:105)
      at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
  cher.java:85)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
  troller.run(InProcessBuildActionExecuter.java:81)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
  a:33)
      at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
  a:24)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
  ssBuildActionExecuter.java:39)
      at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
  ssBuildActionExecuter.java:29)
      at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
      at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
  a:171)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
  execute(CommandLineActionFactory.java:237)
      at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
  execute(CommandLineActionFactory.java:210)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
  meValidationAction.java:35)
      at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
  meValidationAction.java:24)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
  CommandLineActionFactory.java:206)
      at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
  CommandLineActionFactory.java:169)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
  ortingAction.java:33)
      at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
  ortingAction.java:22)
      at org.gradle.launcher.Main.doAction(Main.java:33)
      at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
  trap.java:54)
      at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
  ava:35)
      at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
      at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
  va:30)
      at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
      at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
  Caused by: org.gradle.api.InvalidUserDataException: Cannot perform signing task
  ':signArchives' because it has no configured signatory
      at org.gradle.plugins.signing.Sign.generate(Sign.groovy:162)
      at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
      at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskF
  actory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
  ctTask.java:570)
      at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
  ctTask.java:553)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteAction(ExecuteActionsTaskExecuter.java:80)
      at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
  ecuteActions(ExecuteActionsTaskExecuter.java:61)
      ... 47 more

**Comment by vThinkBeyondVM** [comment]
I was yesterday building latest jars using gradlew.bat, it was failing with exactly the same issue posted above. Now I have created Maven project and modified POM file with required dependencies, it is working fine.

**Comment by michaelrice** [comment]
Please see this:
https://github.com/yavijava/yavijava/wiki/How-to-submit-bug-reports#help-me-help-you

**Comment by michaelrice** [comment]
I would like your java version, but I did add a change to the build file now that will only run the signing task if it is a production release, and I marked the version as a snapshot.

**Comment by asdubey80** [comment]
java version "1.7.0_65"

**Comment by asdubey80** [comment]
Although build was failed but I found jar file in lib directory. i used this jar file and it worked. The time taken to snapshot dvSwitch is now in seconds 20 to 40 seconds as compare to 3 to 6 minutes.

**Comment by asdubey80** [comment]
I think this issue is fixed. I verified performance and its improved. Without this fix the snapshot operation on dvSwitch 5.5 was taking about 9 minutes and now its taking 2 minutes 44 seconds. With vijava also its taking 2 min 44 seconds.

**Comment by asdubey80** [comment]
Thanks for your quick response. When you will be publishing this jar?

**Comment by michaelrice** [comment]
@asdubey80 Now that the fix has been verified by you, I will go ahead and merge the code, then try to cut a release later today, or tomorrow.

**Comment by asdubey80** [comment]
So this release will be vijava-6.0.01 or 02? We are picking this jar from http://mvnrepository.com/artifact/com.toastcoders/yavijava/6.0.01 so is this updated jar will be available at same location?

**Comment by michaelrice** [comment]
@asdubey80 It will be 6.0.02 I will have a release ready pretty soon. Someone opened an issue in #129 that I want to fix before the next release. I am currently updating my windows systems to test some changes I have that should fix the issue, but its going really slow because my only windows system is on a very old system.
