### ISSUE TITLE
DocumentException: null Nested exception: null for "void" methods

### ISSUE THREAD

**Issue by zimnytunczyk** [yavijava/yavijava#125]
I tried few void methods like HostStorageSystem#refreshStorageSystem() or HostStorageSystem#rescanAllHba(). They ends up with exception because unMarshall try to process null. I've tested with ESXi 5.5.0.

Exception in thread "main" java.rmi.RemoteException: VI SDK invoke exception:org.dom4j.DocumentException: null Nested exception: null
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:76)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:203)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:95)
    at com.vmware.vim25.ws.VimStub.rescanAllHba(VimStub.java:3699)

**Comment by michaelrice** [comment]
Hello @zimnytunczyk can you check this out: [help me help you](https://github.com/yavijava/yavijava/wiki/How-to-submit-bug-reports#help-me-help-you)

**Comment by zimnytunczyk** [comment]
Not an issue. I turn on DEBUG logs and find out SocketTimeoutException. That's why response was null. I set bigger ReadTimeout (ServiceInstance#getServerConnection().getVimService().getWsc().setReadTimeout()) and it works great.

2015-08-21 16:35:12,103 DEBUG  [WSClient] Caught an IOException. Reading ErrorStream for results. 
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:150)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)

**Comment by michaelrice** [comment]
I feel like we should bubble that exception up in a RemoteException. Im going to open an issue related to this.

Would you say steps to reproduce are:
1. make call to any method that causes a timeout before the return happen
2. cause a socket timeout to happen
3. attempt to parse null body

?

**Comment by zimnytunczyk** [comment]
Below is full stack trace. As you can see first exception was logged with DEBUG. I reproduce this because I type 10 instead of 10000 (10 seconds) in ServiceInstance#getServerConnection().getVimService().getWsc().setReadTimeout().

2015-08-21 16:35:12,103 DEBUG  [WSClient] Caught an IOException. Reading ErrorStream for results. 
java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:150)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:911)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:703)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1534)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.vmware.vim25.ws.WSClient.post(WSClient.java:169)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:93)
    at com.vmware.vim25.ws.VimStub.refreshStorageSystem(VimStub.java:3866)
    at com.vmware.vim25.mo.HostStorageSystem.refreshStorageSystem(HostStorageSystem.java:243)
    at VoidMethodsTest.main(VoidMethodsTest.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
2015-08-21 16:35:12,109 ERROR  [WSClient] Exception caught while invoking method: RefreshStorageSystem 
java.rmi.RemoteException: VI SDK invoke exception:org.dom4j.DocumentException: null Nested exception: null
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:76)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:203)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:95)
    at com.vmware.vim25.ws.VimStub.refreshStorageSystem(VimStub.java:3866)
    at com.vmware.vim25.mo.HostStorageSystem.refreshStorageSystem(HostStorageSystem.java:243)
    at VoidMethodsTest.main(VoidMethodsTest.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
