### ISSUE TITLE
Using SSL certificates with YAVIJava

### ISSUE THREAD

**Issue by Shuchi05** [yavijava/yavijava#154]
Hi, 

I am trying to implement the certificate handling with the YAVIJava. I am doing the following:
- Update the host certificate in the local keystore 
- System.setProperty("javax.net.ssl.trustStore", storePath)
- call ServiceInstance(serverIP, username, password, false)

I am getting the following error : 
    javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:92)
    at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1667)
    at com.vmware.vim25.mo.ServiceInstance.retrieveServiceContent(ServiceInstance.java:248)
    at com.vmware.vim25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:127)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:79)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69)

I have checked the truststore and the certificate is updated. Do you have any idea why this could be happening?

Thanks,
Shuchita

**Comment by michaelrice** [comment]
You might take a look at this: http://stackoverflow.com/questions/4764611/java-security-invalidalgorithmparameterexception-the-trustanchors-parameter-mus

good luck.
