### ISSUE TITLE
Missing field 'network' from com.vmware.vim25.CannotAccessNetwork fault

### ISSUE THREAD

**Issue by alex-lata** [yavijava/yavijava#159]
Hi,

I am getting the following exception while getting the events with a _EventHistoryCollector_:

```
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
    java.lang.NoSuchFieldException: network
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:123)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:212)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:93)
    at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:106)
    at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:98)
    at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:146)
    at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:170)
    at com.vmware.vim25.mo.EventHistoryCollector.getLatestPage(EventHistoryCollector.java:56)
...
Caused by: java.lang.NoSuchFieldException: network
    at java.lang.Class.getField(Class.java:1703)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:233)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:329)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:329)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:322)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:329)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:322)
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:204)
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:120)
    ... 12 more
Caused by: java.lang.RuntimeException: java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
    java.lang.NoSuchFieldException: network
    at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:149)
    at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:170)
    at com.vmware.vim25.mo.EventHistoryCollector.getLatestPage(EventHistoryCollector.java:56)
    ... 4 more
Caused by: java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
    java.lang.NoSuchFieldException: network
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:123)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:212)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:93)
    at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:106)
    at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:98)
    at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:146)
    ... 7 more
Caused by: java.lang.NoSuchFieldException: network
    at java.lang.Class.getField(Class.java:1703)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:233)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:329)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:329)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:322)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:329)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:322)
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:204)
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:120)
    ... 12 more
```

The problem seems to come from the fact that 'network' property is missing from [CannotAccessNetwork](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.fault.CannotAccessNetwork.html) fault. By looking at the property description it looks like this was added in vSphere 6.0, and probably forgotten in yavijava.

It is not obvious how to produce a test class to highlight the problem mostly because I am pretty sure it's circumstantial. Maybe this will help: this exception is generated by my events collector once a virtual machine is cloned. 

Here's my environment:
Java: 1.8.0_66-b17
yavijava:  6.0.03
vSphere: 6.0.0

Any help would be appreciated! Thanks!
Alex

**Comment by michaelrice** [comment]
Can you provide me the soap envelope that contains the `CannotAccessNetwork` fault? Ill write the test real quick and get this added for you. To capture that XML you would need to enable TRACE level logging. I dont need any of the other output (and there will be TONS). Please make sure if you do post a lot because you arent sure which part I need check those logs for usernames, passwords, host names.. It will all be there in plain text.

**Comment by alex-lata** [comment]
Hi,

Well, this was fast! Thank you!
The problem comes from _VMOnVirtualIntranet_ which extends the _CannotAccessNetwork_. This is what I got:

```
<Event xsi:type="MigrationResourceWarningEvent">
    <key>2765251</key>
    <chainId>2765250</chainId>
    <createdTime>2016-04-25T13:59:13.659Z</createdTime>
    <userName>test_user</userName>
    <datacenter>
        <name>TEST-DC</name>
        <datacenter type="Datacenter">datacenter-3</datacenter>
    </datacenter>
    <computeResource>
        <name>clu1-test</name>
        <computeResource type="ClusterComputeResource">domain-c8</computeResource>
    </computeResource>
    <host>
        <name>esx02-test</name>
        <host type="HostSystem">host-18</host>
    </host>
    <vm>
        <name>test_vm_006</name>
        <vm type="VirtualMachine">vm-446</vm>
    </vm>
    <fullFormattedMessage>Migration of test_vm_006 from esx02-test to esx02-test and resource pool System vDC (c81dc543-38ed-4c6b-b11d-e1beb74b2de9) in TEST-DC: Network interface 'Network adapter 1' uses network 'Internal Network', which is a 'virtual intranet'.</fullFormattedMessage>
    <template>false</template>
    <fault>
        <fault xsi:type="VMOnVirtualIntranet">
            <device>Network adapter 1</device>
            <backing>Internal Network</backing>
            <connected>false</connected>
            <network type="Network">network-86</network>
        </fault>
        <localizedMessage>Network interface 'Network adapter 1' uses network 'Internal Network', which is a 'virtual intranet'.</localizedMessage>
    </fault>
    <dstPool>
        <name>System vDC (c81dc543-38ed-4c6b-b11d-e1beb74b2de9)</name>
        <resourcePool type="ResourcePool">resgroup-31</resourcePool>
    </dstPool>
    <dstHost>
        <name>esx02-test</name>
        <host type="HostSystem">host-18</host>
    </dstHost>
</Event>
```

Hope it's going to be enough for your tests.
Alex

**Comment by michaelrice** [comment]
What you provided does not contain a soap envelope with the actual fault. Here is an example of the response Im looking for:

``` XML
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault><faultcode>ServerFaultCode</faultcode><faultstring>Cannot complete login due to an incorrect user name or password.</faultstring><detail><InvalidLoginFault xmlns="urn:vim25" xsi:type="InvalidLogin"></InvalidLoginFault></detail></soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>
```

This example is from an invalid login.

**Comment by alex-lata** [comment]
Hi,

Actually, the SOAP envelope does not contain only the fault. The response contains all the available events, and among them there's one containing a fault. I guess that the problem comes from the conversion(xml->java) of this event.
Well, this should give you missing info:

```
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Body>
        <QueryEventsResponse xmlns="urn:vim25">
            <returnval xsi:type="TaskEvent">
                <key>2765311</key>
                <chainId>2765311</chainId>
                <createdTime>2016-04-25T15:33:33.179Z</createdTime>
                <userName>USERNAME</userName>
                <datacenter>
                    <name>TEST_DATACENTER</name>
                    <datacenter type="Datacenter">datacenter-3</datacenter>
                </datacenter>
                <computeResource>
                    <name>clu1-test</name>
                    <computeResource type="ClusterComputeResource">domain-c8</computeResource>
                </computeResource>
                <host>
                    <name>esx02-test</name>
                    <host type="HostSystem">host-18</host>
                </host>
                <vm>
                    <name>test_vm_006</name>
                    <vm type="VirtualMachine">vm-446</vm>
                </vm>
                <fullFormattedMessage>Task: Clone virtual machine</fullFormattedMessage>
                <info>
                    <key>task-1284</key>
                    <task type="Task">task-1284</task>
                    <name>CloneVM_Task</name>
                    <descriptionId>VirtualMachine.clone</descriptionId>
                    <entity type="VirtualMachine">vm-446</entity>
                    <entityName>test_vm_006</entityName>
                    <state>queued</state>
                    <cancelled>false</cancelled>
                    <cancelable>true</cancelable>
                    <reason xsi:type="TaskReasonUser">
                        <userName>USERNAME</userName>
                    </reason>
                    <queueTime>2016-04-25T15:33:33.177924Z</queueTime>
                    <eventChainId>2765311</eventChainId>
                </info>
            </returnval>
            <returnval xsi:type="MigrationResourceWarningEvent">
                <key>2765312</key>
                <chainId>2765311</chainId>
                <createdTime>2016-04-25T15:33:33.229999Z</createdTime>
                <userName>USERNAME</userName>
                <datacenter>
                    <name>TEST_DATACENTER</name>
                    <datacenter type="Datacenter">datacenter-3</datacenter>
                </datacenter>
                <computeResource>
                    <name>clu1-test</name>
                    <computeResource type="ClusterComputeResource">domain-c8</computeResource>
                </computeResource>
                <host>
                    <name>esx02-test</name>
                    <host type="HostSystem">host-18</host>
                </host>
                <vm>
                    <name>test_vm_006</name>
                    <vm type="VirtualMachine">vm-446</vm>
                </vm>
                <fullFormattedMessage>Migration of test_vm_006 from esx02-test to esx02-test and resource pool System vDC (c81dc543-38ed-4c6b-b11d-e2beb74b2de9) in TEST_DATACENTER: Network interface 'Network adapter 1' uses network 'Internal Network', which is a 'virtual intranet'.</fullFormattedMessage>
                <template>false</template>
                <fault>
                    <fault xsi:type="VMOnVirtualIntranet">
                        <device>Network adapter 1</device>
                        <backing>Internal Network</backing>
                        <connected>false</connected>
                        <network type="Network">network-86</network>
                    </fault>
                    <localizedMessage>Network interface 'Network adapter 1' uses network 'Internal Network', which is a 'virtual intranet'.</localizedMessage>
                </fault>
                <dstPool>
                    <name>System vDC (c81dc543-38ed-4c6b-b11d-e2beb74b2de9)</name>
                    <resourcePool type="ResourcePool">resgroup-31</resourcePool>
                </dstPool>
                <dstHost>
                    <name>esx02-test</name>
                    <host type="HostSystem">host-18</host>
                </dstHost>
            </returnval>
            <returnval xsi:type="VmBeingClonedEvent">
                <key>2765313</key>
                <chainId>2765311</chainId>
                <createdTime>2016-04-25T15:33:33.323999Z</createdTime>
                <userName>USERNAME</userName>
                <datacenter>
                    <name>TEST_DATACENTER</name>
                    <datacenter type="Datacenter">datacenter-3</datacenter>
                </datacenter>
                <computeResource>
                    <name>clu1-test</name>
                    <computeResource type="ClusterComputeResource">domain-c8</computeResource>
                </computeResource>
                <host>
                    <name>esx02-test</name>
                    <host type="HostSystem">host-18</host>
                </host>
                <vm>
                    <name>test_vm_006</name>
                    <vm type="VirtualMachine">vm-446</vm>
                </vm>
                <fullFormattedMessage>Cloning test_vm_006 on host esx02-test in TEST_DATACENTER to clone_test_vm_006 on host esx02-test</fullFormattedMessage>
                <template>false</template>
                <destFolder>
                    <name>TEST-FOLDER</name>
                    <folder type="Folder">group-v422</folder>
                </destFolder>
                <destName>clone_test_vm_006</destName>
                <destHost>
                    <name>esx02-test</name>
                    <host type="HostSystem">host-18</host>
                </destHost>
            </returnval>
            <returnval xsi:type="VmClonedEvent">
                <key>2765314</key>
                <chainId>2765311</chainId>
                <createdTime>2016-04-25T15:33:33.866999Z</createdTime>
                <userName>USERNAME</userName>
                <datacenter>
                    <name>TEST_DATACENTER</name>
                    <datacenter type="Datacenter">datacenter-3</datacenter>
                </datacenter>
                <computeResource>
                    <name>clu1-test</name>
                    <computeResource type="ClusterComputeResource">domain-c8</computeResource>
                </computeResource>
                <host>
                    <name>esx02-test</name>
                    <host type="HostSystem">host-18</host>
                </host>
                <vm>
                    <name>clone_test_vm_006</name>
                    <vm type="VirtualMachine">vm-469</vm>
                </vm>
                <fullFormattedMessage>Clone of test_vm_006 completed</fullFormattedMessage>
                <template>false</template>
                <sourceVm>
                    <name>test_vm_006</name>
                    <vm type="VirtualMachine">vm-446</vm>
                </sourceVm>
            </returnval>
        </QueryEventsResponse>
    </soapenv:Body>
</soapenv:Envelope>
```

Thanks,

**Comment by michaelrice** [comment]
Ill just add the missing bits because obviously they are missing. I cant recreate your issue though. The response envelopes you have provided successfully parse into the objects they should with out throwing any exceptions. Im sure if I had more insight into what you were doing and had all the logs I could make the test, but in this case I dont see a reason to bother wasting any more time on it when its obvious the field is missing.

**Comment by michaelrice** [comment]
@a-lata if you wouldnt mind just pulling down the code with this patch, doing a local build of it and try that jar before I merge it that would be great.

**Comment by alex-lata** [comment]
Hi,

Everything works smoothly! You can go on with the merge.

Thank you!
