### ISSUE TITLE
RemoteException: VI SDK invoke exception:org.dom4j.DocumentException: null Nested exception: null

### ISSUE THREAD

**Issue by Tsovak** [yavijava/yavijava#170]
```
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy.company.ru", 3128));
        URLConnection urlConnection = new URL(url_).openConnection(proxy);
        urlConnection.setConnectTimeout(80000);
        urlConnection.setReadTimeout(80000);

        si_ = new ServiceInstance(urlConnection.getURL(), username_, password_, true); // throws exception 


```

I get exception 

```
Exception in thread "main" java.rmi.RemoteException: VI SDK invoke exception:org.dom4j.DocumentException: null Nested exception: null
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:76)
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:203)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:95)
    at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1665)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:85)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69)
    at VirtualMachine.Connection.connect(Connection.java:58)
    at Main.main(Main.java:11)


```

ESXi 5,5
yavijava 5.5.11 and and above
where is the reason?

**Comment by Tsovak** [comment]
`
 Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy.***.ru", 3128));
        URLConnection urlConnection = new URL(url_).openConnection(proxy);
        urlConnection.setConnectTimeout(80000);
        urlConnection.setReadTimeout(80000);
        URL url = urlConnection.getURL();

```
    si_ = new ServiceInstance(urlConnection.getURL(), username_, password_, true);
```

`

inside WSClient.post(String soapMsg){
 HttpURLConnection postCon = (HttpURLConnection) baseUrl.openConnection();

created new connection with no proxy and timeout
