### ISSUE TITLE
JAX-B support for returned classes

### ISSUE THREAD

**Issue by ecornely** [yavijava/yavijava#174]
I would like to use yavijava to provide information about a VM as a RESTService.
It seems that the public fields and the use of lombok always end up in classes that are not usable with JAX-B.

My simple program to test and try serialization is trying to marshall VirtualMachineConfigInfo and GuestInfo classes but always fails.

Would be an improvement to have those beans respect the java beans standard.

**Comment by michaelrice** [comment]
Can you give me an example of what youre talking about, and how to recreate the failure you are seeing?

**Comment by ecornely** [comment]
`ServiceInstance serviceInstance = c.getServiceInstance(managerURL);
    Folder rootFolder = serviceInstance.getRootFolder();
    VirtualMachine vm = (VirtualMachine) new InventoryNavigator(rootFolder).searchManagedEntity("VirtualMachine", "myMachine");
    VirtualMachineConfigInfo config = vm.getConfig();
    JAXBContext.newInstance(VirtualMachineConfigInfo.class).createMarshaller().marshal(config, System.out);`

This gives : `Class has two properties of the same name "parentEnabled"
	this problem is related to the following location:
		at public java.lang.Boolean com.vmware.vim25.VirtualMachineForkConfigInfo.getParentEnabled()
		at com.vmware.vim25.VirtualMachineForkConfigInfo
		at public com.vmware.vim25.VirtualMachineForkConfigInfo com.vmware.vim25.VirtualMachineConfigInfo.forkConfigInfo
		at com.vmware.vim25.VirtualMachineConfigInfo
	this problem is related to the following location:
		at public java.lang.Boolean com.vmware.vim25.VirtualMachineForkConfigInfo.parentEnabled
		at com.vmware.vim25.VirtualMachineForkConfigInfo
		at public com.vmware.vim25.VirtualMachineForkConfigInfo com.vmware.vim25.VirtualMachineConfigInfo.forkConfigInfo
		at com.vmware.vim25.VirtualMachineConfigInfo

	at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:91)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:445)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:277)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123)
	at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:462)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)`

**Comment by michaelrice** [comment]
``` java
ServiceInstance serviceInstance = c.getServiceInstance(managerURL);
Folder rootFolder = serviceInstance.getRootFolder();
VirtualMachine vm = (VirtualMachine) new InventoryNavigator(rootFolder).searchManagedEntity("VirtualMachine", "nrbo2die-dv10");
VirtualMachineConfigInfo config = vm.getConfig();
JAXBContext.newInstance(VirtualMachineConfigInfo.class).createMarshaller().marshal(config, System.out);
```

```
Class has two properties of the same name "parentEnabled"
    this problem is related to the following location:
        at public java.lang.Boolean com.vmware.vim25.VirtualMachineForkConfigInfo.getParentEnabled()
        at com.vmware.vim25.VirtualMachineForkConfigInfo
        at public com.vmware.vim25.VirtualMachineForkConfigInfo com.vmware.vim25.VirtualMachineConfigInfo.forkConfigInfo
        at com.vmware.vim25.VirtualMachineConfigInfo
    this problem is related to the following location:
        at public java.lang.Boolean com.vmware.vim25.VirtualMachineForkConfigInfo.parentEnabled
        at com.vmware.vim25.VirtualMachineForkConfigInfo
        at public com.vmware.vim25.VirtualMachineForkConfigInfo com.vmware.vim25.VirtualMachineConfigInfo.forkConfigInfo
        at com.vmware.vim25.VirtualMachineConfigInfo

    at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:91)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:445)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:277)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124)
    at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123)
    at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
    at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
    at javax.xml.bind.ContextFinder.find(ContextFinder.java:462)
    at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
    at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
```

**Comment by michaelrice** [comment]
I tried to reformat your comment but github was freaking out on me when I would save it. I just moved it all into my comment above so no one has to go to pastebin.

**Comment by michaelrice** [comment]
Looking at this more carefully, this isn't fixable at the library level without breaking other things. Let me explain what's happening and what your options are.

**The cause**

Every vim25 data class declares `public` fields *and* uses Lombok `@Getter`/`@Setter`:

```java
public class VirtualMachineForkConfigInfo extends DynamicData {
    @Getter @Setter public Boolean parentEnabled;
    ...
}
```

JAXB's default introspection mode (`PUBLIC_MEMBER`) sees both the public field *and* the synthesized `getParentEnabled()` and counts them as two properties with the same name — hence the error. This is by design: the public fields exist so you can write `vm.config.hardware.numCPU` directly, and yavijava's own SOAP serializer (`XmlGenDom`) doesn't go through JAXB.

**Why we won't fix it in the library**

The cleanest library-side fix would be `@XmlAccessorType(XmlAccessType.FIELD)` on `DynamicData` (or a `package-info.java` for `com.vmware.vim25`). That tells JAXB to use fields only and ignore the Lombok-generated getters. One annotation, fixes ~1100 generated classes.

The cost: adds a compile-time dep on `jakarta.xml.bind-api` (or `javax.xml.bind`) to every consumer of yavijava — including the majority who'll never marshal anything with JAXB. Since Java 9 JAXB isn't bundled with the JDK anymore, that's a real dep, not a no-op.

Pushing that dep on everyone for a feature few people use isn't a good trade.

**What to do instead**

*If you control the consumer (most likely):* Add a single `package-info.java` to your own project under `com.vmware.vim25`:

```java
@jakarta.xml.bind.annotation.XmlAccessorType(jakarta.xml.bind.annotation.XmlAccessType.FIELD)
package com.vmware.vim25;
```

JAXB will pick that up at runtime and treat all classes in the package as field-access. No library change needed.

*If you're building a REST service (which is what you said):* JAXB is probably the wrong tool in 2026 — Jackson has become the default for REST/JSON work and handles this with config rather than annotations:

```java
ObjectMapper mapper = new ObjectMapper();
mapper.setVisibility(mapper.getSerializationConfig().getDefaultVisibilityChecker()
    .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
    .withGetterVisibility(JsonAutoDetect.Visibility.NONE));
String json = mapper.writeValueAsString(vm.getConfig());
```

*If you want a clean public API:* Build small DTOs containing just the fields your REST consumers actually need, and copy from the vim25 objects. Exposing internal SOAP-binding types as your wire format is a leaky abstraction (deep object graphs, MOR references that mean nothing outside the JVM, version skew on every vSphere upgrade).

Closing as won't-fix. Reopen with details if you hit something the workarounds don't cover.
