### ISSUE TITLE
Property collector throws a runtime exception when retrieving VM update

### ISSUE THREAD

**Issue by ChristianNerriere-eaton** [yavijava/yavijava#179]
Sometimes, when the blocking method **waitForUpdatesEx** is released, it throws the following exception:

```
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
    java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.eaton.pqsoft.virtualization.vmware.VMwarePropertiesMonitor$Poller.run(VMwarePropertiesMonitor.java:372)[136:virtualization-vmware-impl:0.2.1]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_40]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_40]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_40]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_40]
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
    at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)[134:com.eaton.pqsoft.emc4j.thirdparty.yavijava-bundle:6.0.4]
    ... 12 more
```

It appears when the vcenter sents an update of a VM, typically a power state change.
We use the version 6.0.04 of Yavijava with Java 8.
Thanks.
Christian

**Comment by michaelnetapp** [comment]
Yep, I too am seeing this issue.  Any additional information, workaround, ETA on a fix?
We use version 6.0.04 of Yavijava with Java 7.  I'm seeing the issue with vCenter 6.0 U1 specifically.

**Comment by michaelrice** [comment]
In all honesty I no longer work in a role that exposes me to VMWare so I dont have a lab, and dont have access to equipment, or software anymore so I couldnt possibly provide an ETA. Im happy to accept pull requests. I have outlined how to [contribute](https://github.com/yavijava/yavijava/wiki/Contributing) in the wiki if you are interested in helping out.

**Comment by ChristianNerriere-eaton** [comment]
Hello,
The exception is thrown when VMware response contains an update of a field of type `byte[]`. The equivalent xsd type is `base64Binary` and is not managed by the library. Example: field  **vmxConfigChecksum** of class **VirtualMachineConfigInfo**.
To correct the problem, add the following lines:
```
    else if ("base64Binary".equals(type)) {
        field.set(object, Base64.getDecoder().decode(value));
    }
```
at line 130 of the method **setObjectField** of the class **ReflectUtil**.
Maybe the RuntimeException thrown when a unmanaged type is found should be replaced by a simple log to avoid to crash the current deserialization process.

Chris

**Comment by mike-tutkowski** [comment]
Thanks, @ChrisNerr! I grabbed the code you referenced above and am testing it out in the gradle branch.

If I open a PR, are there still people involved in this project who can examine and commit the changes?

**Comment by michaelrice** [comment]
@mike-tutkowski yes. please include a test with your change. I was planning to cut a release this weekend because some folks have hit me up on gitter.im asking for a release of whats currently in the gradle branch

**Comment by mike-tutkowski** [comment]
Due to the fact that Base64 is a Java 8 class (and I don't think we can assume a Java 8 runtime will necessarily be in use all the time when running with this library), I decided to go this route:

        else if ("base64Binary".equals(type)) {
            field.set(object, DatatypeConverter.parseBase64Binary(value));
        }

@michaelrice Would you be able to guide me a bit on how to write a test for YAVIJAVA that depends on the reconfigure virtual machine event? I have a little Java app I wrote (I can attach it for your reference) to reproduce the problem, but it requires a real vCenter Server + ESXi + VM environment. I was able to run my app beforehand to see that the problem exists, update the code in the JAR file, then re-test and see that the problem is no longer present.

**Comment by mike-tutkowski** [comment]
[Yavijava_Test.java.txt](https://github.com/yavijava/yavijava/files/966551/Yavijava_Test.java.txt)

**Comment by michaelrice** [comment]
@mike-tutkowski I think the `Base64` class that @ChrisNerr was referring to was from apache commons which is already pulled in by other deps in the library.

As for a test you dont need to make an integration or functional test, you just need to make a unit test. Take a look at the ReflectUtilTest class for some examples. If you need some one on one help head over to the gitter.im chat and I can help you out.

**Comment by michaelrice** [comment]
@mike-tutkowski so Im really confused about why this is even a problem because it looks like we fixed this in #103 and we even have a test with it that loads the XML and parses the response from the server. Can you please run your file that you provided above with TRACE level logging enabled and do so **WITH OUT** your fix in place so we can get the XML payload that is causing the problem?

**Comment by michaelrice** [comment]
hey @mike-tutkowski I setup a 6.0 lab last night and I have your example above running using 6.0.04 and was wondering how long it takes before you are seeing the exception being thrown. 


Edit:  Oh!! I make a change to the VM then stack trace city, and I see the reason why the fix we added in #103 didnt solve this. So if you look at the test we added the payload with the `vmxConfigChecksum` did not have the xsd type sent along with it and in this payload we get back using your example it does

```XML
<soapenv:Body>
<WaitForUpdatesExResponse xmlns="urn:vim25"><returnval><version>3</version><filterSet><filter type="PropertyFilter">session[5264267b-428f-acc8-419c-e92d21700c9d]52b31bb9-6e95-8668-12ad-3c41d4ee402a</filter><objectSet><kind>modify</kind><obj type="VirtualMachine">vm-13</obj><changeSet><name>config.annotation</name><op>assign</op><val xsi:type="xsd:string">foo</val></changeSet><changeSet><name>config.changeVersion</name><op>assign</op><val xsi:type="xsd:string">2017-04-30T14:59:11.934066Z</val></changeSet><changeSet><name>config.vmxConfigChecksum</name><op>assign</op><val xsi:type="xsd:base64Binary">4DpGONXM23mlYX/Sk0tqwJDt84I=</val></changeSet></objectSet></filterSet></returnval></WaitForUpdatesExResponse>
</soapenv:Body>
```

This is an easy fix with what yall have outlined above and now we have a good soap body to make a valid test with!

**Comment by mike-tutkowski** [comment]
I noticed that I had to change the disk resource shares to trigger the error.

It also requires update one or two of vSphere 6, I believe.

On Apr 30, 2017, at 8:56 AM, Michael Rice <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @mike-tutkowski<https://github.com/mike-tutkowski> I setup a 6.0 lab last night and I have your example above running using 6.0.04 and was wondering how long it takes before you are seeing the exception being thrown.

**Comment by mike-tutkowski** [comment]
Here you go, @michaelrice:

/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:60457,suspend=y,server=n -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/htmlconverter.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/javafx-doclet.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/lib/tools.jar:/Users/solidfire/Documents/yavijava/YAVIJAVA-Test/target/classes:/Users/solidfire/.m2/repository/com/toastcoders/yavijava/6.0.04/yavijava-6.0.04.jar:/Users/solidfire/.m2/repository/org/apache/httpcomponents/httpclient/4.3.5/httpclient-4.3.5.jar:/Users/solidfire/.m2/repository/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/solidfire/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/solidfire/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/Users/solidfire/.m2/repository/org/apache/directory/studio/org.dom4j.dom4j/1.6.1/org.dom4j.dom4j-1.6.1.jar:/Users/solidfire/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:/Users/solidfire/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/solidfire/.m2/repository/org/projectlombok/lombok/1.16.6/lombok-1.16.6.jar:/Users/solidfire/.m2/repository/org/apache/logging/log4j/log4j-api/2.8.2/log4j-api-2.8.2.jar:/Users/solidfire/.m2/repository/org/apache/logging/log4j/log4j-core/2.8.2/log4j-core-2.8.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar" Yavijava_Test
Connected to the target VM, address: '127.0.0.1:60457', transport: 'socket'
0 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. ServiceContent
235 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. ServiceContent
439 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UserSession
607 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. ManagedObjectReference
734 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. ManagedObjectReference
981 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UpdateSet
1
37590 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UpdateSet
37616 [main] ERROR com.vmware.vim25.ws.WSClient  - Exception caught while invoking method: WaitForUpdatesEx
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
We have an error.
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
43487 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UpdateSet
We have an error.
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
43491 [main] ERROR com.vmware.vim25.ws.WSClient  - Exception caught while invoking method: WaitForUpdatesEx
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
43644 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UpdateSet
43647 [main] ERROR com.vmware.vim25.ws.WSClient  - Exception caught while invoking method: WaitForUpdatesEx
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
We have an error.
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
43799 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UpdateSet
We have an error.
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
43809 [main] ERROR com.vmware.vim25.ws.WSClient  - Exception caught while invoking method: WaitForUpdatesEx
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more
43940 [main] DEBUG com.vmware.vim25.ws.XmlGenDom  - Parsing XML payload from server. UpdateSet
We have an error.
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:125)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.waitForUpdatesEx(VimStub.java:134)
	at com.vmware.vim25.mo.PropertyCollector.waitForUpdatesEx(PropertyCollector.java:119)
	at Yavijava_Test.main(Yavijava_Test.java:53)
Caused by: java.lang.RuntimeException: Unexpected Type at setObjectField: java.lang.Objectval
	at org.doublecloud.ws.util.ReflectUtil.setObjectField(ReflectUtil.java:130)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:332)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:349)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:237)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:122)
	... 5 more

**Comment by mike-tutkowski** [comment]
In ReflectUtil.setObjectField, the "bolded" code below solves the problem (based on @ChrisNerr's comment):

        else if ("double".equals(type)) {
            field.set(object, Double.parseDouble(value));
        }
        else if ("Double".equals(type)) {
            field.set(object, new Double(value));
        }
##         else if ("base64Binary".equals(type)) {
##             field.set(object, DatatypeConverter.parseBase64Binary(value));
##         }
        else {
            throw new RuntimeException("Unexpected Type at setObjectField: " + field.getType().getCanonicalName() + field.getName());
        }

I choose to use DatatypeConverter.parseBase64Binary instead of code from Base64 (as Chris suggested) because we already use DatatypeConverter.parseBase64Binary in one other place in ReflectUtil.java.

**Comment by michaelrice** [comment]
@mike-tutkowski did you want to send a pull request with the fix and a test or would you rather me just do it?

**Comment by mike-tutkowski** [comment]
Whatever is easier for you or whatever you prefer from a change-management standpoint.

If you'd prefer that I do it, I should be able to do so tomorrow (I'm away for the rest of the day today).

Thanks!

On Apr 30, 2017, at 1:51 PM, Michael Rice <notifications@github.com<mailto:notifications@github.com>> wrote:


@mike-tutkowski<https://github.com/mike-tutkowski> did you want to send a pull request with the fix and a test or would you rather me just do it?

**Comment by michaelrice** [comment]
Ill take care of it today so it can be part of the 6.0.05 release, plus Monday when I go back to work I have to get back to OpenStack stuff.

**Comment by michaelnetapp** [comment]
Thanks so much.  We really appreciate this work.

On Apr 30, 2017 2:28 PM, Michael Rice <notifications@github.com> wrote:

Ill take care of it today so it can be part of the 6.0.05 release, plus Monday when I go back to work I have to get back to OpenStack stuff.

**Comment by mike-tutkowski** [comment]
Awesome – thanks!

On Apr 30, 2017, at 2:31 PM, michaelnetapp <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks so much. We really appreciate this work.

On Apr 30, 2017 2:28 PM, Michael Rice <notifications@github.com<mailto:notifications@github.com>> wrote:

Ill take care of it today so it can be part of the 6.0.05 release, plus Monday when I go back to work I have to get back to OpenStack stuff.
