### ISSUE TITLE
IllegalAccessExceptions in XmlGen for transient fields

### ISSUE THREAD

**Issue by neil-greenwood** [yavijava/yavijava#18]
During a WS call, there are intermittent exceptions thrown within XmlGen when it tries to serialize the parameters for the WS call. On the occasions when exceptions are thrown, many occur.

They look similar to the following stacktrace:

```
2014-11-12 08:05:03,407 [main] ERROR com.vmware.vim25.ws.XmlGen  - IllegalAccessException caught.
java.lang.IllegalAccessException: Class com.vmware.vim25.ws.XmlGen can not access a member of class com.vmware.vim25.PropertyFilterSpec with modifiers "private static final transient"
    at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:109)
    at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:261)
    at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:253)
    at java.lang.reflect.Field.get(Field.java:376)
    at com.vmware.vim25.ws.XmlGen.toXML(XmlGen.java:169)
    at com.vmware.vim25.ws.XmlGen.toXML(XmlGen.java:112)
    at com.vmware.vim25.ws.XmlGen.toXML(XmlGen.java:76)
    at com.vmware.vim25.ws.XmlGen.toXML(XmlGen.java:58)
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:91)
    at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:96)
    at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:107)
```

I think I have a fix for this (not serializing transient fields), which I'm in the process of testing now. I'll create a pull-request when it's ready.

**Comment by michaelrice** [comment]
Let me know if there is anything I can help with on this @neil-greenwood

**Comment by neil-greenwood** [comment]
I got held up by work :-( and the unit tests failing because I hadn't entered parameters in the VcenterInfo.properties file.

I've pushed a change to my forked repo now, just doing some more testing.

Should we be mocking the interactions in the unit tests, rather than requiring access to a real Vcenter?

**Comment by michaelrice** [comment]
Yeah we totally should be. Technically what we have right now is an integration test.

**Comment by neil-greenwood** [comment]
Logged issue #20.
