### ISSUE TITLE
ClassCastException while trying to read the environment variables from a guest virtual machine

### ISSUE THREAD

**Issue by alex-lata** [yavijava/yavijava#186]
Hello,

I am getting the following exception while trying to get the environment variables from a guest virtual machine:

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.lang.String;
    at com.vmware.vim25.ws.VimStub.readEnvironmentVariableInGuest(VimStub.java:4723)
    at com.vmware.vim25.mo.GuestProcessManager.readEnvironmentVariableInGuest(GuestProcessManager.java:61)
```

Long story short, instead of getting the env variables as an array of Strings I end up with a List of Strings.

Here's a test class to reproduce this problem:

``` java
public class TestReadEnvironmentVariableInGuest {
    private static final Logger LOGGER = LoggerFactory.getLogger(TestReadEnvironmentVariableInGuest.class.getPackage().getName());

    public static void main(final String[] args) {
        // Read the args.
        if (args.length < 6) {
            throw new RuntimeException("Usage: vCenterAddress vCenterUsername vCenterPassword guestVirtualMachineMORef guestVirtualMachineUsername  guestVirtualMachinePassword");
        }

        final Iterator<String> args_ = Arrays.asList(args).iterator();

        final String vCenterAddress = args_.next();
        final String vCenterUsername = args_.next();
        final String vCenterPassword = args_.next();

        final String guestVirtualMachineMORef = args_.next();
        final String guestVirtualMachineUsername = args_.next();
        final String guestVirtualMachinePassword = args_.next();

        try {
            // Build the service instance.
            final ServiceInstance serviceInstance = buildServiceInstance(vCenterAddress, vCenterUsername, vCenterPassword);

            try {
                // Get the operations manager.
                final GuestOperationsManager guestOperationsManager = serviceInstance.getGuestOperationsManager();
                if (guestOperationsManager != null) {

                    // Host virtual machine.
                    final ManagedObjectReference vmMoRef = new ManagedObjectReference();
                    vmMoRef.setType("VirtualMachine");
                    vmMoRef.setVal(guestVirtualMachineMORef);
                    final VirtualMachine virtualMachine = new VirtualMachine(serviceInstance.getServerConnection(), vmMoRef);

                    // Auth.
                    final NamePasswordAuthentication auth = new NamePasswordAuthentication();
                    auth.username = guestVirtualMachineUsername;
                    auth.password = guestVirtualMachinePassword;
                    final GuestAuthManager authManager = guestOperationsManager.getAuthManager(virtualMachine);
                    authManager.ValidateCredentialsInGuest(auth);

                    // Guest process manager.
                    final GuestProcessManager guestProcessManager = guestOperationsManager.getProcessManager(virtualMachine);
                    LOGGER.debug("Environment variables in guest:");
                    for (final String env : guestProcessManager.readEnvironmentVariableInGuest(auth, new String[0])) {
                        LOGGER.debug(env);
                    }
                }
            } finally {
                // Logout.
                serviceInstance.getSessionManager().logout();
            }
        } catch (final Exception exception) {
            LOGGER.error("Fail.", exception);
        }
    }

    private static ServiceInstance buildServiceInstance(final String address, final String username, final String password)
    throws RemoteException, MalformedURLException {
        return new ServiceInstance(new URL("https", address, -1, "/sdk"), username, password, true);
    }
}
```

The source of the problem seems to be ReflectUtil#parseToObject method which simply returns the List of values for the 'array of Strings' case:

``` java
    public static Object parseToObject(String type, List<String> values) {
        if ("String".equals(type) || "string".equals(type)) {
            return values.get(0);
        }
        else if ("String[]".equals(type)) {
            return values;
        }
        ...
```

The following code should fix the issue:

``` java
    public static Object parseToObject(String type, List<String> values) {
        if ("String".equals(type) || "string".equals(type)) {
            return values.get(0);
        }
        else if ("String[]".equals(type)) {
            return values.toArray(new String[values.size()]);
        }
```

Though I' m not sure of the impacts of a such change.

Some extra info:
YAVIJAVA version is 6.0.04 (I am also able to reproduce it on the 'gradle' branch).
VSphere version is 6.0.0
Operating system of the guest virtual machine is a Debian (VMWare Tools installed) .

Thank you,
Alex

**Comment by michaelrice** [comment]
Can you provide the full stack trace and possibly the TRACE logs that have the SOAP payloads in them? If you can provide those logs be sure to remove any passwords that are included in them.

**Comment by michaelrice** [comment]
So after reviewing this more I dont need that stack trace, but the TRACE logs would be invaluable here. I mainly just need the SOAP envelope that has the response with `GuestProcessManager` and the return it has from calling that `readEnvironmentVariableInGuest()` method. This would allow me to wirte a good test around the ReflectUtil class.

**Comment by alex-lata** [comment]
Hi Michael,
Thank you for your quick reply! 
Here's my request for getting the environment variables:

```
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><ReadEnvironmentVariableInGuest xmlns="urn:vim25"><_this type="GuestProcessManager">guestOperationsProcessManager</_this><vm type="VirtualMachine">vm-XXX</vm><auth xsi:type="NamePasswordAuthentication"><interactiveSession xsi:type="xsd:boolean">false</interactiveSession><username>root</username><password>XXXXXX</password></auth></ReadEnvironmentVariableInGuest></soapenv:Body></soapenv:Envelope>
```

And here's the response:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<ReadEnvironmentVariableInGuestResponse xmlns="urn:vim25"><returnval>CONSOLE=/dev/console</returnval><returnval>HOME=/root</returnval><returnval>init=/sbin/init</returnval><returnval>runlevel=S</returnval><returnval>INIT_VERSION=sysvinit-2.88</returnval><returnval>TERM=linux</returnval><returnval>COLUMNS=80</returnval><returnval>BOOT_IMAGE=/vmlinuz-3.2.0-4-amd64</returnval><returnval>PATH=/sbin:/usr/sbin:/bin:/usr/bin</returnval><returnval>RUNLEVEL=S</returnval><returnval>PREVLEVEL=N</returnval><returnval>SHELL=/bin/bash</returnval><returnval>PWD=/</returnval><returnval>previous=N</returnval><returnval>LINES=25</returnval><returnval>rootmnt=/root</returnval><returnval>VMWARE_GIO_MODULE_DIR=1/usr/lib/vmware-tools/libconf/lib/gio/modules</returnval><returnval>GIO_MODULE_DIR=/usr/lib/vmware-tools/libconf/lib/gio/modules</returnval><returnval>VMW_SETUGID_TEST=1</returnval><returnval>USER=root</returnval></ReadEnvironmentVariableInGuestResponse>
</soapenv:Body>
</soapenv:Envelope>
```

Let me know if you need any further information.

Best,
Alex

**Comment by michaelrice** [comment]
Hi Alex,

Thanks a lot for this info. I went though the source and found a bunch of places this should be a bug and Im kind of surprised Ive never run into it before after all these years with as many places as it shows up. This was a really good catch. Ive got the tests written and the fix you suggested works fine. Ill be adding the patch later this weekend. Thanks again!

-mike

**Comment by alex-lata** [comment]
Hi Mike, 

You are welcome and thank you as well!

Alex
