### ISSUE TITLE
Invalid argument 'endTime' in querySpec for vimstub.queryPerf() API

### ISSUE THREAD

**Issue by bbsantosh** [yavijava/yavijava#189]
Hi 

Hi below is the stack trace for the API, I try to iterate over a list of VM in the Datacenter and collect metrics for each of it. I build the spec with the following way 

```java
List<PerfQuerySpec> pqsList = new ArrayList<PerfQuerySpec>();
Calendar curTime = si.currentTime();
Calendar endTime = (Calendar) curTime.clone();
VirtualMachine vm = (VirtualMachine) new InventoryNavigator(si.getRootFolder()).searchManagedEntity(
								"VirtualMachine", vm.name());
Calendar startTime = (Calendar) curTime.clone();

    
startTime.setTimeInMillis(curTime.getTimeInMillis() - (15 * 60 * 1000L));
Calendar endTime = (Calendar) curTime.clone();
querySpecification.setEntity(vm.getMOR());
querySpecification.setStartTime(startTime);

querySpecification.setEndTime(endTime);
System.out.println("The end time is " + endTime.getTime());
	
querySpecification.setIntervalId(300);
pqsList.add(querySpecification);
PerfEntityMetricBase[] retrievedStats = si.getServerConnection().getVimService().queryPerf(pmRef, pqsList.toArray(new PerfQuerySpec[pqsList.size()]));

```
When i execute the above in a loop for list of all the avaliable vm's i get the below stack trace. It works fine with vijava. Any change that i need to do after including the yavi lib. Please advice 

2016-11-03 10:11:42,817 [pool-44-thread-3] ERROR invoke(WSClient.java:99) - Exception caught while invoking method: QueryPerf
com.vmware.vim25.InvalidArgument: A specified parameter was not correct: querySpec[0].endTime
        at sun.reflect.GeneratedConstructorAccessor446.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:246)
        at com.vmware.vim25.ws.XmlGenDom.parseSoapFault(XmlGenDom.java:149)
        at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:107)
        at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
        at com.vmware.vim25.ws.VimStub.queryPerf(VimStub.java:1451)

**Comment by michaelrice** [comment]
Can you include TRACE logging so I can take a look at the XML payloads coming and going from the server? Please be sure to remove any passwords from those logs before you post them.

**Comment by bbsantosh** [comment]
[trace.txt](https://github.com/yavijava/yavijava/files/588324/trace.txt)
Hi Michael, 

I have attached the trace file, please find the attachment. THe exact log statement can be found at    2016-11-14 03:13:16,120 [Thread-94] ERROR invoke(WSClient.java:99) - Exception caught while invoking method: QueryPerf
com.vmware.vim25.InvalidArgument: A specified parameter was not correct: querySpec.startTime, querySpec.endTime

Please let me know if you need any more details. 

Thanks
Santosh

**Comment by michaelrice** [comment]
What version of VIJAVA does this work on? From what I can see the payloads on this are properly formed and the only difference in ones where it fails vs ones where its working is the MOREF of the VM you are trying to get and millisecond in the `endTime` which is expected anyway.

**Comment by michaelrice** [comment]
Also what version of yavijava are you using?

**Comment by bbsantosh** [comment]
I am using the YAVIJAVA version 6.0.04 and vijava which i was using vijava55b20130927

**Comment by bbsantosh** [comment]
Any updates on it, or any pointers for me to look into.

**Comment by michaelrice** [comment]
Im sorry I dont see anything that could be causing this problem. The payloads for calls that work and calls that fail look the same. The only thing I can think of is you might try the latest code from the gradle branch.  I dont expect it to work any differently but its worth a try. There have been a few bugs fixed since the last release but I dont think any of them would be related to this issue.

**Comment by michaelrice** [comment]
Michael investigated with full TRACE logs in 2016 and could not reproduce — the XML payloads appeared correctly formed. The reporter was on 6.0.04 (many versions old). No further activity in 8+ years. Closing as stale.
