### ISSUE TITLE
Yavijava Hello World sample not working for me...Need Help

### ISSUE THREAD

**Issue by gescoffery** [yavijava/yavijava#220]
I'm trying to run the yavijava Hello World sample (https://github.com/yavijava/hello_world_yavijava) and I'm running into errors. I don't believe it's an SSL problem as I set the flag to ignore the cert.
Every time it tries to create the ServiceInstance the logger catches an error 
"com.vmware.vim25.ws.VimStub - error detected at url ..."

It blows up at the setVimNameSpace(namespace); line in the ServiceInstance.java file. 
        VimPortType vimService = trustManager != null ? new VimPortType(url.toString(), trustManager) : new VimPortType(url.toString(), ignoreCert);
        vimService.getWsc().setVimNameSpace(namespace);

I know the url is good because if I use the same URL when I try the VMWare Sample it works.
I'd like to use YAVIJAVA to create everything for me or 

Any ideas? 

Below is a snippet of the VM Ware Sample

        VimService vimService = new VimService();
        VimPortType vimPort = vimService.getVimPort();

        Map<String, Object> ctxt = ((BindingProvider) vimPort).getRequestContext();
        ctxt.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, url);
        ctxt.put(BindingProvider.SESSION_MAINTAIN_PROPERTY, true);

        ManagedObjectReference serviceInstance = new ManagedObjectReference();
        serviceInstance.setType("ServiceInstance");
        serviceInstance.setValue("ServiceInstance");

        try {
            ServiceContent serviceContent = vimPort.retrieveServiceContent(serviceInstance);
            vimPort.login(serviceContent.getSessionManager(), user, password, null);

            // print out the product name, server type, and product version
            System.out.println(serviceContent.getAbout().getFullName());
            System.out.println("Server type is " + serviceContent.getAbout().getApiType());
            System.out.println("API version is " + serviceContent.getAbout().getVersion());

            vimPort.logout(serviceContent.getSessionManager());
            }

**Comment by michaelrice** [comment]
I would need to see your whole stacktrace at the very least to get an idea of whats going on. Also, the vmware code you provided is not relevant to YAVIJAVA.

**Comment by gescoffery** [comment]
The error is happening on another network but i copied everything by hand below

ERROR com.vmware.vim25.ws.VimStub  - Error detected for url: https://30.11.100.50/sdk ignoreSSL: true 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:408)  at com.vmware.vim25.ws.ClientCreator.getClient(ClientCreator.java:30) at com.vmware.vim25.ws.VimStub.<init>(VimStub.java:56) at com.vmware.vim25.VimPortType.<init>(VimPortType.java:39) at com.vmware.vim25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:120) at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:79) at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69) at com.toastcoders.samples.Main.main(Main.java:47)

Caused by: java.lang.NoClassDefFoundError: org/dom4j/DocumentException at com.vmware.vim25.ws.SoapClient.<init>(SoapClient.java:45) at com.vmware.vim25.ws.WSClient.<init>(WSClient.java:72) at com.vmware.vim25.ws.WSClient.<init>(WSClient.java:69)
... 11 more


Caused by: java.lang.ClassNotFoubdException: org.dom4j.DocumentationException at java.net.URLClassLoader$1.run(URLClassLoader.java:372) at java.net.URLClassLoader$1.run(URLClassLoader.java:361) at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
... 14 more


Exception in thread "main" java.lang.NullPointerException at com.vmware25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:121) at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:79) at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69) at com.toastcoders.samples.Main.main(Main.java:47)

**Comment by gescoffery** [comment]
I only included the snippet to show how the structure is put together as it differs from YAVIJAVA

**Comment by michaelrice** [comment]
Looks like I need to add a requirement to the build.gradle for dom4j on that sample.

If you put dom4j in your class path that should fix this problem for you.

**Comment by gescoffery** [comment]
I'll give it a try...thanks

**Comment by michaelrice** [comment]
After following the instructions given on the referenced sample I am unable to reproduce this and also didnt even need to add dom4j because it is pulled down by the requirement for yavijava

    git clone git@github.com:yavijava/hello_world_yavijava.git
    cd hello_world_yavijava/
    ./gradlew fatJar
    java -jar build/libs/hello_world_yavijava-1.0.jar "administrator@vsphere.maas" '<mypassword>' 192.168.88.60
    Server Time: Thu Dec 01 18:43:41 CST 2016
    Session: vmware_soap_session="67141073aea63985e79e3a01f44601eec213ae80"; Path=/; HttpOnly; Secure;
    Logging off.

```
→ find . -iname "*dom4j*" -print
./.idea/libraries/Gradle__dom4j_dom4j_1_6_1.xml
./.idea/libraries/Gradle__org_apache_directory_studio_org_dom4j_dom4j_1_6_1.xml
./build/tmp/expandedArchives/dom4j-1.6.1.jar_de47lu5y69755ex3vpsa9sdmb
./build/tmp/expandedArchives/dom4j-1.6.1.jar_de47lu5y69755ex3vpsa9sdmb/org/dom4j
./build/tmp/expandedArchives/org.dom4j.dom4j-1.6.1.jar_6wnrxqwpkljz8lbk2nj2t1ble
./build/tmp/expandedArchives/org.dom4j.dom4j-1.6.1.jar_6wnrxqwpkljz8lbk2nj2t1ble/lib/dom4j-1.6.1.jar
```
