### ISSUE TITLE
[question]return ClassNotFoundException in using task.waitForTask() where invoking removeDatastoreEx_Task()

### ISSUE THREAD

**Issue by zhenmie365** [yavijava/yavijava#225]
#@   It's well when I only use HostDatastoreSystem.removeDatastoreEx_Task(datastoreUuidArray) to remove NFS datastores from host.
   but if running task.waitForTask() from the task returned by HostDatastoreSystem.removeDatastoreEx_Task(datastoreUuidArray),the error is appeared : 
`[main] ERROR org.doublecloud.ws.util.TypeUtil  - ClassNotFoundException caught for type: ArrayOfHostDatastoreSystemDatastoreResult
java.lang.ClassNotFoundException: com.vmware.vim25.ArrayOfHostDatastoreSystemDatastoreResult
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at org.doublecloud.ws.util.TypeUtil.getVimClass(TypeUtil.java:100)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:246)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:329)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:322)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:204)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:120)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:212)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:93)
	at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:106)
	at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:98)
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:146)
	at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:170)
	at com.vmware.vim25.mo.Task.getTaskInfo(Task.java:51)
	at com.vmware.vim25.mo.Task.waitForTask(Task.java:187)
	at com.vmware.vim25.mo.Task.waitForTask(Task.java:132)
	at com.sunment.cloud.vmware.vm.VmOperationTest.testDs(VmOperationTest.java:553)
	at com.sunment.cloud.vmware.vm.VmOperationTest.main(VmOperationTest.java:566)
4    [main] ERROR com.vmware.vim25.ws.WSClient  - Exception caught while invoking method: RetrieveProperties
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
	java.lang.NullPointerException
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:123)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:212)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:93)
	at com.vmware.vim25.ws.VimStub.retrieveProperties(VimStub.java:106)
	at com.vmware.vim25.mo.PropertyCollector.retrieveProperties(PropertyCollector.java:98)
	at com.vmware.vim25.mo.ManagedObject.retrieveObjectProperties(ManagedObject.java:146)
	at com.vmware.vim25.mo.ManagedObject.getCurrentProperty(ManagedObject.java:170)
	at com.vmware.vim25.mo.Task.getTaskInfo(Task.java:51)
	at com.vmware.vim25.mo.Task.waitForTask(Task.java:187)
	at com.vmware.vim25.mo.Task.waitForTask(Task.java:132)`
   I'm using yavijava 6.0.03,in vsphere 6.0 environment.

**Comment by michaelrice** [comment]
Can you enable TRACE logging and provide me the XML payloads coming and going to the server? It looks like the docs say it should return a Task but the error you are posting looks like its `ArrayOfHostDatastoreSystemDatastoreResult` I would need to see the XML to be sure though.

Be sure to remove your passwords from the XML before you paste it.

**Comment by michaelrice** [comment]
Also can you post some sample code I can run too.

**Comment by zhenmie365** [comment]
I'm sorry that I can't get the meaning of "TRACE logging and provide me the XML payloads coming and going to the server".Can you show the process?
And process of the error coming out is following:
`Task task = HostSystem.getHostDatastoreSystem().removeDatastoreEx_Task(datastoreList);
task.waitForTask(3000, 5000);`
If only running the first line, no error occured,and host removed the datastore(NFS) success in VC.The successful result has come out in the task logging of vSphere Web Client.
If two line all running,the error occured.
I found that the Description of the type named HostDatastoreSystemDatastoreResult  in vSphere api 6.0 is following "Contains result of remove datastore request. Used as return value by RemoveDatastoreEx_Task". And the class named ArrayOfHostDatastoreSystemDatastoreResult can't find in yavijava 6.0.03.jar.Is the question point there?

**Comment by michaelrice** [comment]
In your `log4j.properties` I need you to enable TRACE logging on `com.vmware`

Here is an example file: https://github.com/yavijava/hello_world_yavijava/blob/master/src/main/resources/log4j.properties

On line 8 I have `info` but I need you to make that `trace`

Then rerun your code and provide me the logs that come from it. Those logs will include the XML payloads coming and going from the server.

**Comment by zhenmie365** [comment]
ok.I got it!

Perhaps I will send the logs to you three days later,because I have no vmware environment this three days.

**Comment by zhenmie365** [comment]
[log4jForArrayHostDatastore.txt](https://github.com/yavijava/yavijava/files/681912/log4jForArrayHostDatastore.txt)

The log above is the output of console , running code is following.

[codeOfBugs.txt](https://github.com/yavijava/yavijava/files/681916/codeOfBugs.txt)

**Comment by michaelrice** [comment]
As I suspected. The documentation says one thing and the API actually does another. Right now its "working as coded" because I code this based on what the docs say but there is a bug in the docs thus a bug in the code. Ive added this to the TODO list for 6.5 support. 
Thanks!

**Comment by zhenmie365** [comment]
My pleasure!
By the way, do documentation mean vSphere api 6.0?
