### ISSUE TITLE
AlarmManager.createAlarm() not working properly

### ISSUE THREAD

**Issue by ghost** [yavijava/yavijava#229]
https://github.com/yavijava/yavijava-samples/blob/gradle/src/main/java/com/vmware/vim25/mo/samples/alarm/CreateVmAlarm.java

This sample seems not work,it throws exception:

Exception in thread "main" com.vmware.vim25.InvalidArgument: A specified parameter was not correct: 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at com.vmware.vim25.ws.XmlGenDom.fromXml(XmlGenDom.java:251)
	at com.vmware.vim25.ws.XmlGenDom.parseSoapFault(XmlGenDom.java:149)
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:107)
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253)
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96)
	at com.vmware.vim25.ws.VimStub.createAlarm(VimStub.java:2544)
	at com.vmware.vim25.mo.AlarmManager.createAlarm(AlarmManager.java:150)
	at com.mycompany.api.CreateVmAlarm.main(CreateVmAlarm.java:80)

The value validation is somehow a blackbox.

**Comment by michaelrice** [comment]
That error means you have an error in the spec file and vSphere wasnt able to validate it in order to create your alarm.

**Comment by ghost** [comment]
I've tested it in vsphere SDK 6.0 by running: 
 ./run.sh com.vmware.alarms.VMPowerStateAlarm --url https://<my-vcenter>/sdk --username administrator@vsphere.local --password mypassword --vmname vm1 --alarm testAlarm

WARNING: Java is now set to trust all SSL certificates.

-- VMware samples in Java --

Successfully created Alarm: alarm-201


The SDK is here: https://code.vmware.com/web/dp/doc/preview?id=1503#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F338ffa03-f04b-469c-9d71-4071f3948c0e%2F84b7d0ca-ab70-4e07-b4bd-4caf8f9745d7%2Fdoc%2FPG_Appx_Sample_Overviews.23.2.html%231007038

However it fails in the yavijava 6.0.03 when I run the sample in this repo (I'm using the same config values for the alarmSpec).  Is this a yavijava bug?

**Comment by michaelrice** [comment]
I dont understand what your last comment means. The SDK you provided a link to is not relevant to this project so Im a little confused. All I know for sure is that the error from your initial report means that vSphere could not validate your spec file.

**Comment by ghost** [comment]
I have done more tests and the issue seems to be caused by vsphere SDK, since yavijava is a light-weight wrapper for the SDK, I think it did the right thing. I'll talk to the vsphere team for solution. Thanks!
