### ISSUE TITLE
[Question] Using yavijava offline (online DTD parsing)

### ISSUE THREAD

**Issue by nE0sIghT** [yavijava/yavijava#240]
Hello.

While trying yavijava in Internet-less environment I'm experienced exception:

```
java.rmi.RemoteException: An error occurred parsing XML with return type: ServiceContent; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:89) ~[yavijava-6.0.05.jar:na]
	at com.vmware.vim25.ws.SoapClient.unMarshall(SoapClient.java:253) ~[yavijava-6.0.05.jar:na]
	at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:96) ~[yavijava-6.0.05.jar:na]
	at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1675) [yavijava-6.0.05.jar:na]
	at com.vmware.vim25.mo.ServiceInstance.retrieveServiceContent(ServiceInstance.java:246) [yavijava-6.0.05.jar:na]
	at com.vmware.vim25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:126) [yavijava-6.0.05.jar:na]
	at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:79) [yavijava-6.0.05.jar:na]
	at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69) [yavijava-6.0.05.jar:na]
	at ru.consyst_oc.vinventory.tasks.ServerTask.run(ServerTask.java:64) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_112]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[na:1.8.0_112]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_112]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_112]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_112]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_112]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_112]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_112]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_112]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_112]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_112]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_112]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_112]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_112]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546) ~[na:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1270) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:264) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1161) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.8.0_112]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[na:1.8.0_112]
	at org.dom4j.io.SAXReader.read(SAXReader.java:465) ~[dom4j-1.6.1.jar:1.6.1]
	at org.dom4j.io.SAXReader.read(SAXReader.java:343) ~[dom4j-1.6.1.jar:1.6.1]
	at com.vmware.vim25.ws.XmlGenDom.fromXML(XmlGenDom.java:81) ~[yavijava-6.0.05.jar:na]
	... 11 common frames omitted
```

dom4j trying to validate online DTD and failed to connect to external server.
What is the proper way to disable xml validation or online DTD processing?

**Comment by michaelrice** [comment]
Maybe something in this post will help: https://stackoverflow.com/questions/1185519/how-to-read-well-formed-xml-in-java-but-skip-the-schema/1185766#1185766

**Comment by nE0sIghT** [comment]
@michaelrice 

Thanks for fast response.

Since I'm using higher level API (yavijava) all XML processing methods (like DocumentBuilder) out of my control as I understand.

I searched some system property or way to define default EntityResolver, however fail to found it.
It is possible for me to include yavijava source directly in my project and set custom EntityResolver in yavijava code, however I want to avoid such way.

**Comment by michaelrice** [comment]
So just guessing here without digging in very much Im guessing you may have to make your own client like we did in the [ApacheHttpClient](https://github.com/yavijava/yavijava/blob/gradle/src/main/java/com/vmware/vim25/ws/ApacheHttpClient.java) and when you are in there you could try various stuff with the 
```java
SaxReader sr = new SaxReader();
sr.setProperty("resolve-dtd-uris", false);
```
Or something similar. Ive never had to do this or mess with dom4j at this low level like this so I really have no idea without digging in further.

**Comment by nE0sIghT** [comment]
I dig this issue and found that there is no way to specify EntityResolver for yavijava because it should be set [prior to Document.read() call at XmlGenDom.java#L81](https://github.com/yavijava/yavijava/blob/gradle/src/main/java/com/vmware/vim25/ws/XmlGenDom.java#L81).
Only implementing own SAXParserFactory, SAXParser, XMLReader and ignoring setEntityResolver method will do the trick, however it will be a dirty hack.

What do you think about checking some system property (eg. yavijava.xml.resolver) for a class name, instantiate such class (if property is not empty) and provide it to SAXReader via setEntityResolver call?

I will create PR if you agree.
