### ISSUE TITLE
yavijava6.0 can not connect to vsphere5.0 or 5.5

### ISSUE THREAD

**Issue by jinweijie0527** [yavijava/yavijava#245]
```java
import com.vmware.vim25.mo.ServiceInstance;

import java.net.MalformedURLException;
import java.net.URL;
import java.rmi.RemoteException;
import java.util.Calendar;

/**
 * Created by iopsdev on 17-9-24.
 */
public class Test {
    public static void main(String[] args)
    {
        if (args.length != 3) {
            System.out.println("Example: java -jar hello_world_yavijava-1.0.jar administrator@vsphere.local password 172.16.214.143");
            System.exit(1);
        }
        // Connection info needed to connect to the vSphere server
        String user = args[0];
        String passwd = args[1];
        // This can be the hostname or ip of the vSphere server
        String host = args[2];

        // the last param of true for ServiceInstance is to ignore SSL
        // Im using true because the default setup most folks use is to have
        // the self signed SSL certs provided during the vSphere install and
        // they have not added those certs to their java keystore.
        // If you do not provide true here the default is false so the cert
        // must be in your keystore, or you will get SSL errors.
        ServiceInstance serviceInstance = null;
        try {
            serviceInstance = new ServiceInstance(new URL("https://" + host + "/sdk"),user, passwd, true);
        } catch (RemoteException e) {
            e.printStackTrace();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        // If you make it this far you have connected and have a valid ServiceInstance which can be used to do something.
        // So lets see what time the server thinks it is.
        Calendar calendar = null;
        try {
            calendar = serviceInstance.currentTime();
        } catch (RemoteException e) {
            e.printStackTrace();
        }
        System.out.println("Server Time: " + calendar.getTime().toString());

        // Now lets see what our Session ID is
        String session = serviceInstance.getServerConnection().getSessionStr();
        System.out.println("Session: " + session);

        // Now lets log off.
        System.out.println("Logging off.");
        serviceInstance.getServerConnection().logout();
    }

}
```

log4j:WARN No appenders could be found for logger (com.vmware.vim25.ws.WSClient).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.rmi.RemoteException: Exception caught trying to invoke method RetrieveServiceContent; nested exception is:
        java.net.ConnectException: Connection timed out (Connection timed out)
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:106)
        at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1675)
        at com.vmware.vim25.mo.ServiceInstance.retrieveServiceContent(ServiceInstance.java:246)
        at com.vmware.vim25.mo.ServiceInstance.constructServiceInstance(ServiceInstance.java:126)
        at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:79)
        at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69)
        at Test.main(Test.java:32)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at com.vmware.vim25.ws.WSClient.post(WSClient.java:168)
        at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:94)
        ... 6 more
Exception in thread "main" java.lang.NullPointerException
        at Test.main(Test.java:43)

**Comment by michaelrice** [comment]
Can you post your TRACE logs here? Im not able to see the problem from what you have posted but I am 100% sure there is not a bug in the lib causing this and it will end up being an issue in usage or vcenter configuration. I use this in production on vcenters from 6.5 all the way back to 4.0 right now. Ill be happy to help you trouble shoot though

**Comment by michaelrice** [comment]
Also from reading the stack trace again you did have a connection time out: `java.net.ConnectException: Connection timed out (Connection timed out)` Thats not going to be the fault of the lib. That is likely a DNS issue or a firewall issue.

**Comment by jinweijie0527** [comment]
@michaelrice thanks for your reply, this is firewall issue.
