### ISSUE TITLE
Plans to release new version(6.0.06) with the minor changes

### ISSUE THREAD

**Issue by lifemanship** [yavijava/yavijava#290]
Hi @michaelrice 
We use [vsphere-cloud-plugin](https://github.com/jenkinsci/vsphere-cloud-plugin) in our jenkins CI. The `vsphere-cloud-plugin` depends on [yavijava](https://github.com/jenkinsci/vsphere-cloud-plugin/blob/master/pom.xml#L95-L96).

Last few months we have been experiencing a network problem with `vsphere-cloud-plugin`, i.e. it fails to connect(Login) to our vcenter with the following  error:
```
com.vmware.vim25.ws.WSClient#invoke: Exception caught while invoking method: Login
com.vmware.vim25.InvalidLogin: Cannot complete login due to an incorrect user name or password.
...
at org.jenkinsci.plugins.vsphere.tools.VSphere.<init>(VSphere.java:75)
at org.jenkinsci.plugins.vsphere.tools.VSphere.connect(VSphere.java:98)
at org.jenkinsci.plugins.vSphereCloud.vSphereInstance(vSphereCloud.java:302)
```

We have made investigation and found that behaviour of `HttpURLConnection`, which is used in [`WSClient`](https://github.com/yavijava/yavijava/blob/gradle/src/main/java/com/vmware/vim25/ws/WSClient.java#L133), can be impacted by system-wide cookie handler [CookieManager](https://docs.oracle.com/javase/8/docs/api/java/net/CookieManager.html). The major problem is that the `CookieManager` overlaps logic provided in [WSClient](https://github.com/yavijava/yavijava/blob/gradle/src/main/java/com/vmware/vim25/ws/WSClient.java#L163-L166) to fill http header `Cookie`. The `vsphere-cloud-plugin` do not use CookieManager, but there is no guarantee that other [plugins](https://github.com/jenkinsci/parameterized-remote-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/RemoteBuildConfiguration.java#L158-L159) avoid it.
As workaroud we have decided to add customization in `vsphere-cloud-plugin` to be able switch between [`WSClient` and `ApacheHttpClient`](https://github.com/yavijava/yavijava/blob/gradle/src/main/java/com/vmware/vim25/ws/ClientCreator.java#L26) 
But we need a new version of `yavijava` which contains that [Fix the cookie handler for ApacheHttpClient](https://github.com/yavijava/yavijava/pull/288/commits/1426f303ccfc43dcbe74d9c4d1eee42fa566148c).

Could you please provide us with new version of the `yavijava`?

Issue in JIRA:
https://issues.jenkins.io/browse/JENKINS-69999

**Comment by michaelrice** [comment]
The project has seen significant active development recently. The 9.0-SNAPSHOT line includes a full vSphere 9.0 WSDL regen, Apache HttpClient 4→5 migration, Java 11→21 target, Observable/Observer removal, SOAP action negotiation fixes for vSphere 6.7/7.x/8.x/9.x, security dependency updates, and a comprehensive new test suite. A snapshot is available via mavenLocal and will be published to Maven Central on the next release cut. Closing this as the release work is actively underway.
