### ISSUE TITLE
All Exceptions casting to RemoteException.

### ISSUE THREAD

**Issue by manthinaa** [yavijava/yavijava#42]
All the exceptions getting while creating ServiceInstance are getting casted in to RemoteException. And those can't cast, ServiceInstance class is throwing ClassCassException instead of the original exception. And following is the stracktrace:
Caused by: java.lang.ClassCastException: java.net.UnknownHostException cannot be cast to java.rmi.RemoteException
    at com.vmware.vim25.ws.WSClient.invoke(WSClient.java:101)
    at com.vmware.vim25.ws.VimStub.retrieveServiceContent(VimStub.java:1665)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:85)
    at com.vmware.vim25.mo.ServiceInstance.<init>(ServiceInstance.java:69)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:963)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:202)
    at com.xxx.xxx.xxx.xxxx.getServiceInstance(ResourceCount.groovy:205)
    ... 58 more

**Comment by zaheena** [comment]
Hey @michaelrice 

Did you get a chance to look at this?

**Comment by michaelrice** [comment]
@zaheena I have not. The statement "All exceptions" is not correct though. Any VMWare exceptions are not casting as such. I am only seeing this happen on connection related exceptions like Anil reported. I do know the VMWare faults all cast properly so I have not made this a big priority.

Is it causing problems for you?

**Comment by zaheena** [comment]
@michaelrice 
We are trying to catch the UnknowHostException which would help us identify the case when a virtual center is not found.

**Comment by michaelrice** [comment]
@zaheena can you email me the logs to my rackspace account so I can see what all logs are getting triggered. From a quick glance this is going to be a pretty painful refactor to fix but maybe the logs will show me somewhere else I could add a fix.

**Comment by michaelrice** [comment]
@zaheena What about this? Can you ask Bud how terrible he thinks this would be?

``` diff
diff --git a/src/main/java/com/vmware/vim25/ws/WSClient.java b/src/main/java/com/vmware/vim25/ws/WSClient.java
index 73114d5..4872e8e 100644
--- a/src/main/java/com/vmware/vim25/ws/WSClient.java
+++ b/src/main/java/com/vmware/vim25/ws/WSClient.java
@@ -98,7 +98,12 @@ public class WSClient extends SoapClient {
             log.error("Exception caught while invoking method: " + methodName, e1);
             // Fixes issue-28 still need to write a test which may require
             // further refacotring but this at least gets the InvalidLogin working.
-            throw (RemoteException) e1;
+            if (e1 instanceof RemoteException) {
+                throw (RemoteException) e1;
+            }
+            else {
+                throw new RemoteException("Too bad the decision was made in 5.5 to do this terrible RemoteException thing ",e1);
+            }
         }
         finally {
             if (is != null) {

```

This might be a sensible work around.. I hate it, but with out a seriously major refactor I dont see a lot of options..

It seems as though everything was turned into this RemoteException thing, and so non vmware exceptions will basically fail. I dont know what else to do for a short term fix

**Comment by zaheena** [comment]
@michaelrice 
I will ask him and get back.
Meanwhile I will email you the error log.

**Comment by michaelrice** [comment]
@zaheena Thanks

This will at least make it so you can get that unknown host.. you will have to catch RemoteException then do a getCause() on it to get the next throwable which would be the UnknownHost
