### ISSUE TITLE
java.lang.NoSuchFieldException: protocolEndpoint

### ISSUE THREAD

**Issue by jaidmoha3** [yavijava/yavijava#48]
When trying retrievepropertiesEx, for collecting HostSystem and VirtualMachines, am seeing the below issue,  
  com.vmware.vim25.ws.WSClient                                      Exception caught while invoking method: RetrievePropertiesEx java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
    java.lang.NoSuchFieldException: protocolEndpoint
    at com.vmware.vim25.ws.XmlGenDom.fromXML(Unknown Source)
    at com.vmware.vim25.ws.SoapClient.unMarshall(Unknown Source)
    at com.vmware.vim25.ws.WSClient.invoke(Unknown Source)
    at com.vmware.vim25.ws.VimStub.retrievePropertiesEx(Unknown Source)
    at com.vmware.vim25.mo.PropertyCollector.retrievePropertiesEx(Unknown Source)

``` java

import static org.junit.Assert.fail;

import java.net.MalformedURLException;
import java.net.URL;
import java.rmi.RemoteException;
import java.util.List;

import org.junit.Test;

import com.vmware.vim25.InvalidProperty;
import com.vmware.vim25.ManagedObjectReference;
import com.vmware.vim25.ObjectSpec;
import com.vmware.vim25.PropertyFilterSpec;
import com.vmware.vim25.PropertySpec;
import com.vmware.vim25.RetrieveOptions;
import com.vmware.vim25.RetrieveResult;
import com.vmware.vim25.RuntimeFault;
import com.vmware.vim25.SelectionSpec;
import com.vmware.vim25.TraversalSpec;
import com.vmware.vim25.mo.ManagedEntity;
import com.vmware.vim25.mo.PropertyCollector;
import com.vmware.vim25.mo.ServiceInstance;
import com.vmware.vim25.mo.util.PropertyCollectorUtil;

public class vCenterCollectionTest {
    private static final String CLUSTER_COMPUTE_RESOURCE = "ClusterComputeResource";
    private static final String PASSWORD = "Vmware123!";
    private static final String USERNAME = "VSPHERE.LOCAL\\Administrator";
    private static final String CLUSTER_MOR = "domain-c39";
    private static final String VCENTER_SERVER = "vcjai6.int.fusionio.com";
    final String VCENTER_SERVER_URL = "https://" + VCENTER_SERVER + "/sdk";
    private static final String SUMMARY = "summary";
    private static final String NAME = "name";
    private static final String RUNTIME = "runtime";
    private static final String CONFIG = "config";
    private static final String VIRTUAL_MACHINE = "VirtualMachine";
    private static final String HOST_SYSTEM = "HostSystem";
    final String[][] inventoryTypeinfo = new String[][] {
        new String[] {
            HOST_SYSTEM, NAME, CONFIG, SUMMARY, RUNTIME,
        }, {
            VIRTUAL_MACHINE, NAME, CONFIG, RUNTIME,
        }
    };

    @Test
    public void collectClusterDetails() throws InvalidProperty, RuntimeFault, RemoteException, MalformedURLException {
        final ManagedObjectReference mor = new ManagedObjectReference();
        mor.setType(CLUSTER_COMPUTE_RESOURCE);
        mor.setVal(CLUSTER_MOR);
        try {
            ServiceInstance si = new ServiceInstance(new URL(VCENTER_SERVER_URL), USERNAME, PASSWORD, true);
            final RetrieveOptions options = new RetrieveOptions();
            options.setMaxObjects(100);
            PropertyCollector prop = si.getPropertyCollector();
            options.setMaxObjects(25);
            final PropertyFilterSpec spec = createInventoryPropertySpec(
                            new ManagedEntity(si.getServerConnection(), mor), inventoryTypeinfo);
            RetrieveResult result = prop.retrievePropertiesEx(new PropertyFilterSpec[] {
                spec
            }, options);
            assert (result != null);

        } catch (RemoteException e) {
            fail(" ExpectedException: " + e.getMessage());
        }
    }

    public PropertyFilterSpec createInventoryPropertySpec(ManagedEntity parentEntity, String[][] typeinfo) {
        return createPropertySpec(parentEntity, typeinfo, getSelectionSpec());
    }

    public static PropertyFilterSpec createPropertySpec(List<ManagedEntity> parentEnties, String[][] typeinfo) {
        final PropertyFilterSpec spec = new PropertyFilterSpec();
        final PropertySpec[] propspecary = PropertyCollectorUtil.buildPropertySpecArray(typeinfo);
        spec.setPropSet(propspecary);
        for (final ManagedEntity parentEntity : parentEnties) {
            final ObjectSpec os = PropertyCollectorUtil.creatObjectSpec(parentEntity.getMOR(), Boolean.FALSE,
                            getSelectionSpec());
            ObjectSpec[] currentSpec = spec.getObjectSet();
            if (currentSpec == null) {
                currentSpec = new ObjectSpec[] {};
            }
            final ObjectSpec[] newSpec = new ObjectSpec[currentSpec.length + 1];
            for (int i = 0; i < currentSpec.length; i++) {
                newSpec[i] = currentSpec[i];
            }
            newSpec[currentSpec.length] = os;
            spec.setObjectSet(newSpec);
        }
        return spec;
    }

    public static PropertyFilterSpec createPropertySpec(ManagedEntity parentEntity, String[][] typeinfo,
                    SelectionSpec[] sSpecs) {
        final PropertySpec[] propspecary = PropertyCollectorUtil.buildPropertySpecArray(typeinfo);
        final ObjectSpec os = new ObjectSpec();
        os.setObj(parentEntity.getMOR());
        os.setSkip(Boolean.FALSE);
        if (sSpecs != null) {
            os.setSelectSet(sSpecs);
        }

        final PropertyFilterSpec spec = new PropertyFilterSpec();
        spec.setObjectSet(new ObjectSpec[] {
            os
        });
        spec.setPropSet(propspecary);
        return spec;
    }

    private static SelectionSpec[] getSelectionSpec() {
        // Recurse through the folders
        final TraversalSpec visitFolders = PropertyCollectorUtil.createTraversalSpec("visitFolders", "Folder",
                        "childEntity", new String[] {
                            "visitFolders", "dcToHf", "dcToVmf", "crToH", "crToRp", "HToVm", "rpToVm", "DsToH", "crToD"
                        });
        final TraversalSpec vAppToRp = PropertyCollectorUtil.createTraversalSpec("vAppToRp", "VirtualApp",
                        "resourcePool", new String[] {
                            "rpToRp", "vAppToRp"
                        });
        // Recurse through all ResourcePools
        final TraversalSpec rpToRp = PropertyCollectorUtil.createTraversalSpec("rpToRp", "ResourcePool",
                        "resourcePool", new String[] {
                            "rpToRp", "rpToVm"
                        });

        // Recurse through all ResourcePools
        final TraversalSpec rpToVm = PropertyCollectorUtil.createTraversalSpec("rpToVm", "ResourcePool", "vm",
                        new SelectionSpec[] {});

        // Traversal through ResourcePool branch
        final TraversalSpec crToRp = PropertyCollectorUtil.createTraversalSpec("crToRp", "ComputeResource",
                        "resourcePool", new String[] {
                            "rpToRp", "rpToVm"
                        });
        // Traversal through host branch
        final TraversalSpec crToH = PropertyCollectorUtil.createTraversalSpec("crToH", "ComputeResource", "host",
                        new SelectionSpec[] {});

        // Traversal through hostFolder branch
        final TraversalSpec dcToHf = PropertyCollectorUtil.createTraversalSpec("dcToHf", "Datacenter", "hostFolder",
                        new String[] {
                            "visitFolders"
                        });

        // Traversal through vmFolder branch
        final TraversalSpec dcToVmf = PropertyCollectorUtil.createTraversalSpec("dcToVmf", "Datacenter", "vmFolder",
                        new String[] {
                            "visitFolders"
                        });

        final TraversalSpec HToVm = PropertyCollectorUtil.createTraversalSpec("HToVm", "HostSystem", "vm",
                        new String[] {
                            "visitFolders"
                        });

        final TraversalSpec DsToH = PropertyCollectorUtil.createTraversalSpec("DsToH", "HostSystem", "datastore",
                        new String[] {
                            "visitFolders"
                        });
        // Traversal through computer resource branch
        final TraversalSpec crToD = PropertyCollectorUtil.createTraversalSpec("crToD", "ComputeResource", "datastore",
                        new SelectionSpec[] {});

        final SelectionSpec[] sSpecs = new SelectionSpec[11];
        sSpecs[0] = visitFolders;
        sSpecs[1] = vAppToRp;
        sSpecs[2] = crToH;
        sSpecs[3] = dcToHf;
        sSpecs[4] = dcToVmf;
        sSpecs[5] = rpToRp;
        sSpecs[6] = rpToVm;
        sSpecs[7] = crToRp;
        sSpecs[8] = HToVm;
        sSpecs[9] = DsToH;
        sSpecs[10] = crToD;
        return sSpecs;
    }
}
```

**Comment by michaelrice** [comment]
Hello @jaidmoha3 It would help when you report issues if you take a look at this:  http://www.softwaretestinghelp.com/how-to-write-good-bug-report/

Its going to be impossible to fix these things you report if you dont include the version, and the steps it takes for me to reproduce.

**Comment by jaidmoha3** [comment]
I am thinking some fields is not implemented :  protocolEndpoint is not implemented 
The source is from the vsphere6 branch . 
Rev 481 from https://github.com/michaelrice/yavijava.git/branches/vsphere_6
Trying to talk to a vSphere Server 6.0 GA 

Retrieving the hosts and virtual machine information for a cluster resource

**Comment by michaelrice** [comment]
@jaidmoha3 Thanks for trying to clear it up, but that doesnt exactly help me reproduce this problem. Let me point you at what a good bug report looks like:
https://github.com/vmware/pyvmomi/issues/194#issue-50756424

See here the reporter gives a pretty detailed description of the problem, and most importantly they provide a sample block of code that can be executed by a developer so the problem can be recreated. I dont need anything extensive here. Just a very minimal amount of code I can run that will recreate the issue.

**Comment by jaidmoha3** [comment]
java.rmi.RemoteException: Exception in SoapClient.invoke:; nested exception is: 
    java.lang.NoSuchFieldException: protocolEndpoint
    at com.vmware.vim25.ws.XmlGenDom.fromXML(Unknown Source)
    at com.vmware.vim25.ws.SoapClient.unMarshall(Unknown Source)
    at com.vmware.vim25.ws.WSClient.invoke(Unknown Source)
    at com.vmware.vim25.ws.VimStub.retrievePropertiesEx(Unknown Source)
    at com.vmware.vim25.mo.PropertyCollector.retrievePropertiesEx(Unknown Source)
    at com.sandisk.fioplugin.services.TestCollection.main(TestCollection.java:53)
Caused by: java.lang.NoSuchFieldException: protocolEndpoint
    at java.lang.Class.getField(Unknown Source)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(Unknown Source)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(Unknown Source)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(Unknown Source)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(Unknown Source)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(Unknown Source)
    at com.vmware.vim25.ws.XmlGenDom.fromXml(Unknown Source)
    at com.vmware.vim25.ws.XmlGenDom.fromXML(Unknown Source)

Full test class with main.

``` java
import java.net.URL;
import java.rmi.RemoteException;
import java.util.List;

import com.vmware.vim25.ManagedObjectReference;
import com.vmware.vim25.ObjectSpec;
import com.vmware.vim25.PropertyFilterSpec;
import com.vmware.vim25.PropertySpec;
import com.vmware.vim25.RetrieveOptions;
import com.vmware.vim25.RetrieveResult;
import com.vmware.vim25.SelectionSpec;
import com.vmware.vim25.TraversalSpec;
import com.vmware.vim25.mo.ManagedEntity;
import com.vmware.vim25.mo.PropertyCollector;
import com.vmware.vim25.mo.ServiceInstance;
import com.vmware.vim25.mo.util.PropertyCollectorUtil;

public class TestCollection {
    private static final String CLUSTER_COMPUTE_RESOURCE = "ClusterComputeResource";
    private static final String PASSWORD = "Flash123!";
    private static final String USERNAME = "VSPHERE.LOCAL\\Administrator";
    private static final String CLUSTER_MOR = "domain-c7";
    private static final String VCENTER_SERVER = "vcjai6.int.fusionio.com";
    final static String VCENTER_SERVER_URL = "https://" + VCENTER_SERVER + "/sdk";
    private static final String SUMMARY = "summary";
    private static final String NAME = "name";
    private static final String RUNTIME = "runtime";
    private static final String CONFIG = "config";
    private static final String VIRTUAL_MACHINE = "VirtualMachine";
    private static final String HOST_SYSTEM = "HostSystem";
    final static String[][] inventoryTypeinfo = new String[][] {
        new String[] {
            HOST_SYSTEM, NAME, CONFIG, SUMMARY, RUNTIME,
        }, {
            VIRTUAL_MACHINE, NAME, CONFIG, RUNTIME,
        }
    };

    public static void main(String[] args) throws Exception {
        final ManagedObjectReference mor = new ManagedObjectReference();
        mor.setType(CLUSTER_COMPUTE_RESOURCE);
        mor.setVal(CLUSTER_MOR);
        try {
            ServiceInstance si = new ServiceInstance(new URL(VCENTER_SERVER_URL), USERNAME, PASSWORD, true);
            final RetrieveOptions options = new RetrieveOptions();
            options.setMaxObjects(100);
            PropertyCollector prop = si.getPropertyCollector();
            options.setMaxObjects(25);
            final PropertyFilterSpec spec = createInventoryPropertySpec(
                            new ManagedEntity(si.getServerConnection(), mor), inventoryTypeinfo);
            RetrieveResult result = prop.retrievePropertiesEx(new PropertyFilterSpec[] {
                spec
            }, options);
            System.out.print(result);
        } catch (RemoteException e) {
            e.printStackTrace();
        }
    }

    public static PropertyFilterSpec createInventoryPropertySpec(ManagedEntity parentEntity, String[][] typeinfo) {
        return createPropertySpec(parentEntity, typeinfo, getSelectionSpec());
    }

    public static PropertyFilterSpec createPropertySpec(List<ManagedEntity> parentEnties, String[][] typeinfo) {
        final PropertyFilterSpec spec = new PropertyFilterSpec();
        final PropertySpec[] propspecary = PropertyCollectorUtil.buildPropertySpecArray(typeinfo);
        spec.setPropSet(propspecary);
        for (final ManagedEntity parentEntity : parentEnties) {
            final ObjectSpec os = PropertyCollectorUtil.creatObjectSpec(parentEntity.getMOR(), Boolean.FALSE,
                            getSelectionSpec());
            ObjectSpec[] currentSpec = spec.getObjectSet();
            if (currentSpec == null) {
                currentSpec = new ObjectSpec[] {};
            }
            final ObjectSpec[] newSpec = new ObjectSpec[currentSpec.length + 1];
            for (int i = 0; i < currentSpec.length; i++) {
                newSpec[i] = currentSpec[i];
            }
            newSpec[currentSpec.length] = os;
            spec.setObjectSet(newSpec);
        }
        return spec;
    }

    public static PropertyFilterSpec createPropertySpec(ManagedEntity parentEntity, String[][] typeinfo,
                    SelectionSpec[] sSpecs) {
        final PropertySpec[] propspecary = PropertyCollectorUtil.buildPropertySpecArray(typeinfo);
        final ObjectSpec os = new ObjectSpec();
        os.setObj(parentEntity.getMOR());
        os.setSkip(Boolean.FALSE);
        if (sSpecs != null) {
            os.setSelectSet(sSpecs);
        }

        final PropertyFilterSpec spec = new PropertyFilterSpec();
        spec.setObjectSet(new ObjectSpec[] {
            os
        });
        spec.setPropSet(propspecary);
        return spec;
    }

    private static SelectionSpec[] getSelectionSpec() {
        // Recurse through the folders
        final TraversalSpec visitFolders = PropertyCollectorUtil.createTraversalSpec("visitFolders", "Folder",
                        "childEntity", new String[] {
                            "visitFolders", "dcToHf", "dcToVmf", "crToH", "crToRp", "HToVm", "rpToVm", "DsToH", "crToD"
                        });
        final TraversalSpec vAppToRp = PropertyCollectorUtil.createTraversalSpec("vAppToRp", "VirtualApp",
                        "resourcePool", new String[] {
                            "rpToRp", "vAppToRp"
                        });
        // Recurse through all ResourcePools
        final TraversalSpec rpToRp = PropertyCollectorUtil.createTraversalSpec("rpToRp", "ResourcePool",
                        "resourcePool", new String[] {
                            "rpToRp", "rpToVm"
                        });

        // Recurse through all ResourcePools
        final TraversalSpec rpToVm = PropertyCollectorUtil.createTraversalSpec("rpToVm", "ResourcePool", "vm",
                        new SelectionSpec[] {});

        // Traversal through ResourcePool branch
        final TraversalSpec crToRp = PropertyCollectorUtil.createTraversalSpec("crToRp", "ComputeResource",
                        "resourcePool", new String[] {
                            "rpToRp", "rpToVm"
                        });
        // Traversal through host branch
        final TraversalSpec crToH = PropertyCollectorUtil.createTraversalSpec("crToH", "ComputeResource", "host",
                        new SelectionSpec[] {});

        // Traversal through hostFolder branch
        final TraversalSpec dcToHf = PropertyCollectorUtil.createTraversalSpec("dcToHf", "Datacenter", "hostFolder",
                        new String[] {
                            "visitFolders"
                        });

        // Traversal through vmFolder branch
        final TraversalSpec dcToVmf = PropertyCollectorUtil.createTraversalSpec("dcToVmf", "Datacenter", "vmFolder",
                        new String[] {
                            "visitFolders"
                        });

        final TraversalSpec HToVm = PropertyCollectorUtil.createTraversalSpec("HToVm", "HostSystem", "vm",
                        new String[] {
                            "visitFolders"
                        });

        final TraversalSpec DsToH = PropertyCollectorUtil.createTraversalSpec("DsToH", "HostSystem", "datastore",
                        new String[] {
                            "visitFolders"
                        });
        // Traversal through computer resource branch
        final TraversalSpec crToD = PropertyCollectorUtil.createTraversalSpec("crToD", "ComputeResource", "datastore",
                        new SelectionSpec[] {});

        final SelectionSpec[] sSpecs = new SelectionSpec[11];
        sSpecs[0] = visitFolders;
        sSpecs[1] = vAppToRp;
        sSpecs[2] = crToH;
        sSpecs[3] = dcToHf;
        sSpecs[4] = dcToVmf;
        sSpecs[5] = rpToRp;
        sSpecs[6] = rpToVm;
        sSpecs[7] = crToRp;
        sSpecs[8] = HToVm;
        sSpecs[9] = DsToH;
        sSpecs[10] = crToD;
        return sSpecs;
    }
}
```

**Comment by michaelrice** [comment]
Im really confused by what you are doing in this code. Most of this is not needed to do a simple property collector. Right now the problem you are running into is not a bug in the code (well the exception part is a bug. It is already reported in #42 though and Im working on a fix for it). Your problem is just that you are doing it wrong.

Can you tell me if this is what you want to do:

Create a property collector that you use to get all the hosts and vms from a given cluster. For the hosts you want some properties, and the vms you want some properties.

**Comment by jaidmoha3** [comment]
Yes, i want exactly the same..  To get all the hosts and vms from a given cluster. For the hosts you want some properties, and the vms you want some properties.

**Comment by michaelrice** [comment]
Ill write you a sample. Ill update this thread when I have it done.

**Comment by jaidmoha3** [comment]
Is this exception same as reported in https://github.com/michaelrice/yavijava/issues/42, 
any work around to get me going with the propertycollector to get the details

**Comment by michaelrice** [comment]
@jaidmoha3 Here is the correct way to do what you are doing. Please keep in mind its very generic and you would need to expand it so you can relate VirtualMachines to HostSystems properly.

https://gist.github.com/michaelrice/1f84f2254c31b6ec2b24

**Comment by michaelrice** [comment]
@jaidmoha3 I just made an update to the sample I made you. Please check it out again. It uses the newer `retrievePropertiesEx()` method you were using in your example.

**Comment by jaidmoha3** [comment]
Thank you much . Please share the fix for issue 42 as well 

Thanks,
Jaidil

**Comment by michaelrice** [comment]
As soon as I have that fix done I will. Its causing me some major headaches.

**Comment by michaelrice** [comment]
If anyone stumbles upon this in the future I turned this sample into a self contained gradle project and put it here: https://github.com/michaelrice/yavijava_cluster_prop_example
