### ISSUE TITLE
getGuestOperationsManager() returning null

### ISSUE THREAD

**Issue by michaelrice** [yavijava/yavijava#50]
A bug has been reported via email saying that the latest version of yavijava has an issue where getGuestOperationsManager() is returning null.

**Comment by michaelrice** [comment]
They now say it works, but just to be sure Im going to leave this open until I have some test cases written around it.

**Comment by michaelrice** [comment]
``` java
public String[] readEnvironmentVariableInGuest(ManagedObjectReference _this, ManagedObjectReference vm, GuestAuthentication auth, String[] names) throws java.rmi.RemoteException, GuestOperationsFault, InvalidState, TaskInProgress, RuntimeFault
{
        Argument[] paras = new Argument[4];
        paras[0] = new Argument("_this", "ManagedObjectReference", _this);
        paras[1] = new Argument("vm", "ManagedObjectReference", vm);
        paras[2] = new Argument("auth", "GuestAuthentication", auth);
        paras[3] = new Argument("names", "String[]", names);
        List vars = (List) wsc.invoke("ReadEnvironmentVariableInGuest", paras, "String[]");       
        return (String[])vars.toArray(new String[vars.size()]);
}
```

**Comment by Shad0w1nk** [comment]
I'm not having the exact issue exposed in this ticket but the code sample fixed my problem. Assuming you have a valid GuestProcessManager and GuestAuthentication, the following code fail with ClassCastException under version 6.0.03 of yavijava:
GuestProcessManager guestProcessManager = ...
GuestAuthentication auth = ...
guestProcessManager.readEnvironmentVariableInGuest(auth, null);

The stacktrace look like this:
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.lang.String;
    at com.vmware.vim25.ws.VimStub.readEnvironmentVariableInGuest(VimStub.java:4723)
    at com.vmware.vim25.mo.GuestProcessManager.readEnvironmentVariableInGuest(GuestProcessManager.java:61)
    ...

Manually crafting the invocation of ReadEnvironmentVariableInGuest with the previous code sample fix the problem. It would be nice if that code could make it's way into master.

**Comment by michaelrice** [comment]
Closing — both layers of this thread are addressed.

**Original report (Apr 2015):** never reproduced; the reporter retracted in the same week ("They now say it works"). The code path is straightforward:

```java
// ServiceInstance.java
public GuestOperationsManager getGuestOperationsManager() {
    return (GuestOperationsManager) createMO(getServiceContent().getGuestOperationsManager());
}
// MorUtil.createExactManagedObject returns null if the MOR is null
```

So `getGuestOperationsManager()` returns null **only when** the server's `ServiceContent` does not include a `GuestOperationsManager` MOR. That happens on pre-5.0 vSphere, on restricted/mocked endpoints, or before the session is fully initialized — by-design behavior, not a bug. If a current user hits null on a modern vCenter, please open a fresh issue with the connection details + ServiceContent dump so we can investigate what the server is returning.

**Sub-comment by @Shad0w1nk (Aug 2016)** — the `ClassCastException: java.util.ArrayList cannot be cast to [Ljava.lang.String;` from `GuestProcessManager.readEnvironmentVariableInGuest` — was a real, separate bug. It was fixed by commit 23a2a8c0 ("Fixes issue in ReflectUtil with String[]") on Nov 5 2016, closing #186. `ReflectUtil.parseToObject("String[]", values)` now correctly returns `values.toArray(new String[values.size()])`. Regression coverage in `XmlGenDomTest.testFromXML_environment_variables_return_as_string_array` and `testFromXML_Folder_GetChildrenTypes`.

Both paths are green in the current `gradle` branch. Closing.
